### ISSUE TITLE
Game sounds fail to load, causing a crash

### ISSUE THREAD

**Issue by alxcenz** [itdelatrisu/opsu#1]
```
c at suzu in ~/Downloads/opsu
% cat .opsu.log
Tue Jul 08 11:35:06 NZST 2014 ERROR:Failed to load file 'combobreak.wav'.
Tue Jul 08 11:35:06 NZST 2014 ERROR:line with format PCM_UNSIGNED 11025.0 Hz, 8 bit, mono, 1 bytes/frame,  not supported.
javax.sound.sampled.LineUnavailableException: line with format PCM_UNSIGNED 11025.0 Hz, 8 bit, mono, 1 bytes/frame,  not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1175)
	at itdelatrisu.opsu.SoundController.loadClip(SoundController.java:158)
	at itdelatrisu.opsu.SoundController.init(SoundController.java:174)
	at itdelatrisu.opsu.states.Splash$1.run(Splash.java:137)
[several repeats of the above error for each sound file]

Tue Jul 08 11:36:52 NZST 2014 ERROR:** Uncaught Exception! **
Tue Jul 08 11:36:52 NZST 2014 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.SoundController.playClip(SoundController.java:223)
	at itdelatrisu.opsu.SoundController.playSound(SoundController.java:247)
	at itdelatrisu.opsu.states.MainMenu.mousePressed(MainMenu.java:317)
	at org.newdawn.slick.state.StateBasedGame.mousePressed(StateBasedGame.java:499)
	at org.newdawn.slick.Input.poll(Input.java:1217)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:641)
	at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:411)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:321)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:149)
```
```
c at suzu in ~/Downloads/opsu
% java -version 
java version "1.7.0_60"
OpenJDK Runtime Environment (IcedTea 2.5.0) (Arch Linux build 7.u60_2.5.0-2-x86_64)
OpenJDK 64-Bit Server VM (build 24.60-b09, mixed mode)
```

The NullPointerException occurs when clicking on the opsu! star on the main menu, causing the game to crash (probably because it's trying to play a sound even though it failed to load?)

**Comment by itdelatrisu** [comment]
Closing this as it's pretty outdated, and #89 addresses a similar issue.
