### ISSUE TITLE
(not a issue) Is the database structure changed in latest commit?

### ISSUE THREAD

**Issue by chong601** [itdelatrisu/opsu#105]
It seems the latest commit (495a7e7f8b01116307c81e3767d68e19c30a8361) has added 2 new columns to the ```beatmap``` database (got an error if I open the 0.9.0 release complaining about only supplied 39 out of 41 columns) 

Stack trace:
```
Thu Jul 02 10:25:09 SGT 2015 ERROR:[SQLITE_ERROR] SQL error or missing database (table beatmaps has 41 columns but 39 values were supplied)
java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (table beatmaps has 41 columns but 39 values were supplied)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.throwex(DB.java:868)
	at org.sqlite.core.NativeDB.prepare(Native Method)
	at org.sqlite.core.DB.prepare(DB.java:211)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:251)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:223)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:83)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:46)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:139)
Thu Jul 02 10:25:24 SGT 2015 ERROR:** Uncaught Exception! **
Thu Jul 02 10:25:24 SGT 2015 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.db.BeatmapDB.updateCacheSize(BeatmapDB.java:192)
	at itdelatrisu.opsu.db.BeatmapDB.clearDatabase(BeatmapDB.java:211)
	at itdelatrisu.opsu.db.BeatmapDB.checkVersion(BeatmapDB.java:153)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:100)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:46)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:139)
```

**Comment by itdelatrisu** [comment]
Yeah, it did - added columns for slider border and MD5 hash.

**Comment by chong601** [comment]
Confirmed.
Only the latest release suffered (since it is released before that commit) from this issue, but everything after the commit will work even if the columns didn't match up.

Meanwhile on other unrelated issue, have you tried NativeBass for the audio part?
That seemed to be an alternative (in my sense, not sure how it ends up...)

**Comment by Bigpet** [comment]
@chong601 

A quote from the NativeBASS page:
>NativeBass is linked and uses BASS library, you also MUST aquire a license of BASS library.

It requires non open software licenses, so I think it's not a very good idea.

**Comment by chong601** [comment]
I checked the BASS licensing and this is the result:
>BASS is free for non-commercial use. If you are a non-commercial entity (eg. an individual) and you are not making any money from your product (through sales, advertising, etc), then you can use BASS in it for free. Otherwise, one of the following licences will be required. 

But then, it doesn't seem that it is GPL-compatible :/
Since I assume that this isn't going for commercial use, I think it is good then....

**Comment by Bigpet** [comment]
I still don't think it's a good idea to use non-free licenses. We really need to ask ourselves what would be the advantage over gstreamer and is it worth it to mix in non-free components for those advantages. The only advantage that I can see at the moment is that it might have a smaller file-size and I don't think that's enough of a reason.

**Comment by chong601** [comment]
the reason i asked about BASS is because i have checked some code examples on their code and it kind of rather accurate (not much of variance in timing) but if licensing is a issue, then GStreamer may only the one that may help solving the offset issue now.

**Comment by itdelatrisu** [comment]
We'll see how the GStreamer switch goes, since it's nearly finished already.  Feel free to implement a player with BASS if you're interested, though -- having more options can't hurt.

I'll close this issue since it's been resolved.  If you have other comments about music players, post them in #78 or create another issue.
