### ISSUE TITLE
Could not connect to database: '.\.opsu_scores.db'.

### ISSUE THREAD

**Issue by won136** [itdelatrisu/opsu#112]
**Version:** 0.10.1
**Build date:** 2015-07-19 04:39
**OS:** Windows 7 (x86)
**JRE:** 1.8.0_25
**Error:** `Could not connect to database: '.\.opsu_scores.db'.`
**Stack trace:**

```
java.sql.SQLException: opening db: '.\.opsu_scores.db': 액세스가 거부되었습니다
    at org.sqlite.core.CoreConnection.open(CoreConnection.java:128)
    at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
    at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
    at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
    at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
    at org.sqlite.JDBC.createConnection(JDBC.java:114)
    at org.sqlite.JDBC.connect(JDBC.java:88)
    at java.sql.DriverManager.getConnection(Unknown Source)
    at java.sql.DriverManager.getConnection(Unknown Source)
    at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
    at itdelatrisu.opsu.db.ScoreDB.init(ScoreDB.java:88)
    at itdelatrisu.opsu.db.DBController.init(DBController.java:47)
    at itdelatrisu.opsu.Opsu.main(Opsu.java:135)
```

**Comment by itdelatrisu** [comment]
Do you have any idea why this happened?  I don't think anyone else has run into this problem, especially not on Windows.

**Comment by chong601** [comment]
i doubt this is related to folder location with "!" in the path...

@itdelatrisu maybe include the path of the folder if a crash happens in the future?

**Comment by abalabahaha** [comment]
Access denied... Are you sure you have the permissions for the current directory?

On a side note, Right clicking jar -> Open with... -> Java(TM) Platform SE Binary runs opsu from C:\Windows\system32 (for me at least), which regular programs don't have write access to. Are you doing that?

**Comment by itdelatrisu** [comment]
@chong601: I think the program should actually detect if that's the case now and show the proper error -- let me know if the checks are still not working, though. x.x

**Comment by won136** [comment]
@itdelatrisu is only my computer problem??

**Comment by itdelatrisu** [comment]
This might be fixed in the latest release if it was launching from system32, since the launch directory is now ignored.
