### ISSUE TITLE
Game.render() failure.

### ISSUE THREAD

**Issue by JOELwindows7** [itdelatrisu/opsu#123]
**Version:** 0.10.1
**Build date:** 2015-07-19 04:39
**OS:** Linux (amd64)
**JRE:** 1.9.0-ea
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:97)
	at itdelatrisu.opsu.Container.start(Container.java:71)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:171)
Caused by: java.lang.NullPointerException
	at itdelatrisu.opsu.downloads.DownloadNode.drawDownload(DownloadNode.java:391)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:321)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```

**Comment by chong601** [comment]
it seems to be a download failure caused opsu! to crash...

**Comment by itdelatrisu** [comment]
Do you remember what you did to make this happen?  Does it happen all the time, or just this once?

From the stack trace, it seems like this wouldn't happen often at all, since the NPE happens for `download` when the object is already checked at the top of the method.  My best guess is that something called `clearDownload()` asynchronously, so storing a reference to the `download` object would resolve this.  Please re-open or add more comments if this doesn't fix the problem.
