### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by muryokuPLF** [itdelatrisu/opsu#135]
So, we managed to fix the other error, but now i'm getting this?
**Version:** 0.11.0
**Build date:** 2015-09-17 13:02
**OS:** Linux (arm)
**JRE:** 1.7.0_79
**Error:** `** Uncaught Exception! **`
**Stack trace:**

```
java.lang.NullPointerException
    at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
    at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
    at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
    at itdelatrisu.opsu.Container.close_sub(Container.java:121)
    at itdelatrisu.opsu.Container.start(Container.java:75)
    at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
```

**Comment by itdelatrisu** [comment]
Is there anything else in your log?  I think the actual issue is that an exception got thrown while initializing the game container, so it shut down immediately and you got this error since images weren't loaded.

**Comment by muryokuPLF** [comment]
this is my log:
Thu Sep 17 15:40:01 UTC 2015 ERROR:** Uncaught Exception! **
Thu Sep 17 15:40:01 UTC 2015 ERROR:/home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: /home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
java.lang.UnsatisfiedLinkError: /home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: /home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1083)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:197)
Thu Sep 17 16:04:43 UTC 2015 ERROR:** Uncaught Exception! **
Thu Sep 17 16:04:43 UTC 2015 ERROR:/home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: /home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
java.lang.UnsatisfiedLinkError: /home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: /home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1083)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:197)
Thu Sep 17 16:11:29 UTC 2015 ERROR:** Uncaught Exception! **
Thu Sep 17 16:11:29 UTC 2015 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
	at itdelatrisu.opsu.Container.close_sub(Container.java:121)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
Thu Sep 17 16:19:15 UTC 2015 ERROR:** Uncaught Exception! **
Thu Sep 17 16:19:15 UTC 2015 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
	at itdelatrisu.opsu.Container.close_sub(Container.java:121)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
Thu Sep 17 16:27:45 UTC 2015 ERROR:** Uncaught Exception! **
Thu Sep 17 16:27:45 UTC 2015 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
	at itdelatrisu.opsu.Container.close_sub(Container.java:121)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
Thu Sep 17 16:45:16 UTC 2015 ERROR:** Uncaught Exception! **
Thu Sep 17 16:45:16 UTC 2015 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
	at itdelatrisu.opsu.Container.close_sub(Container.java:121)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
Thu Sep 17 20:15:46 UTC 2015 ERROR:** Uncaught Exception! **
Thu Sep 17 20:15:47 UTC 2015 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
	at itdelatrisu.opsu.Container.close_sub(Container.java:121)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
Thu Sep 17 20:21:44 UTC 2015 ERROR:** Uncaught Exception! **
Thu Sep 17 20:21:44 UTC 2015 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
	at itdelatrisu.opsu.Container.close_sub(Container.java:121)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
Thu Sep 17 20:22:55 UTC 2015 ERROR:** Uncaught Exception! **
Thu Sep 17 20:22:55 UTC 2015 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
	at itdelatrisu.opsu.Container.close_sub(Container.java:121)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
Thu Sep 17 21:05:14 UTC 2015 ERROR:** Uncaught Exception! **
Thu Sep 17 21:05:14 UTC 2015 ERROR:/home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: /home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
java.lang.UnsatisfiedLinkError: /home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: /home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:197)
Thu Sep 17 21:43:40 UTC 2015 ERROR:** Uncaught Exception! **
Thu Sep 17 21:43:40 UTC 2015 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
	at itdelatrisu.opsu.Container.close_sub(Container.java:121)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)

**Comment by itdelatrisu** [comment]
Okay, that's odd, I can't tell what the issue is from the logs.  From the stack trace, you can see that the error happens in `close_sub()`, which is only called when the game container is being destroyed -- so even if we were to fix this somehow, the game still wouldn't run.  I can't do any other debugging since I can't reproduce your problem.

**Comment by muryokuPLF** [comment]
So there's no way to fix this?

**Comment by itdelatrisu** [comment]
You can run a debugger through the code, but you'd have to do it yourself (e.g. check out the repository, set up an IDE, set breakpoints to find where the error is happening, etc.) because I don't have any way of reproducing the problem.

**Comment by iceblade112** [comment]
@itdelatrisu Did you miss this part?

```
java.lang.UnsatisfiedLinkError: /home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: /home/pi/Desktop/opsu-fc277221496ddbd3f6284926d2fa4f067cb06530/Natives/liblwjgl.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
```

**Comment by itdelatrisu** [comment]
@iceblade112: I think he said he'd fixed that error (from #132), but correct me if I'm wrong.  The timestamps are also pretty spread out.

**Comment by iceblade112** [comment]
@itdelatrisu Ahh, you're right. I didn't see that. Perhaps he has an older lwjgl version?

**Comment by itdelatrisu** [comment]
Cleaning out old issues related to #218, please open another issue if this happens again. Thanks!
