### ISSUE TITLE
Could not connect to database: '.\.opsu_scores.db'.

### ISSUE THREAD

**Issue by FrcAndroid** [itdelatrisu/opsu#145]
**Version:** 0.12.1
**Build date:** 2015-10-02 03:05
**OS:** Windows 7 (x86)
**JRE:** 1.8.0_60
**Error:** `Could not connect to database: '.\.opsu_scores.db'.`
**Stack trace:**
```
java.sql.SQLException: opening db: '.\.opsu_scores.db': Acceso denegado
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:203)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
	at itdelatrisu.opsu.db.ScoreDB.init(ScoreDB.java:88)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:47)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:166)
```
I get this after this error

Failed to write to file 'C:\Windows\system32\.\.opsu.cfg'.
java.io.FileNotFoundException: .\.opsu.cfg (Acceso denegado)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at itdelatrisu.opsu.Options.saveOptions(Options.java:1369)
	at itdelatrisu.opsu.Options.parseOptions(Options.java:1326)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:119)

**Comment by itdelatrisu** [comment]
Sorry for the super late reply.  Anyway, I think this is your problem: https://github.com/itdelatrisu/opsu/issues/112#issuecomment-128445748

Feel free to re-open if you have any more info.
