### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by julroy67** [itdelatrisu/opsu#146]
**Version:** 0.12.1
**Build date:** 2015-10-25 13:31
**OS:** Linux (amd64)
**JRE:** 1.8.0_65
**Error:** `** Uncaught Exception! **`
**Stack trace:**

```
java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I
    at org.lwjgl.openal.AL10.nalGetSourcei(Native Method)
    at org.lwjgl.openal.AL10.alGetSourcei(AL10.java:853)
    at org.newdawn.slick.openal.SoundStore.isMusicPlaying(SoundStore.java:979)
    at org.newdawn.slick.Music.poll(Music.java:66)
    at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:682)
    at itdelatrisu.opsu.Container.gameLoop(Container.java:98)
    at itdelatrisu.opsu.Container.start(Container.java:72)
    at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
```

**Comment by iceblade112** [comment]
Does this perhaps happen when you start opsu! or randomly?

**Comment by Lemmmy** [comment]
Do you even have an audio driver installed?

**Comment by iceblade112** [comment]
@Lemmmy He's using a GNU/Linux distro, so most sound devices should work "out of the box".

**Comment by Lemmmy** [comment]
@iceblade112 This is not necessarily the case.

**Comment by iceblade112** [comment]
@Lemmmy If that's not the case, then there probably isn't a Linux driver. Few vendors support Linux and I don't think a user would be stupid enough to play a sound-based game without sound drivers.
