### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by Xemerau** [itdelatrisu/opsu#149]
Occurs immediately after importing songs on the downloads menu, the bug occurs frequently but I couldn't replicate it reliably
-----
**Version:** 0.12.1
**Build date:** 2015-11-16 10:29
**OS:** Linux (amd64)
**JRE:** 1.7.0_91
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:722)
	at org.newdawn.slick.opengl.renderer.ImmediateModeOGLRenderer.glDeleteTextures(ImmediateModeOGLRenderer.java:145)
	at org.newdawn.slick.opengl.TextureImpl.release(TextureImpl.java:257)
	at org.newdawn.slick.Image.destroy(Image.java:1553)
	at itdelatrisu.opsu.beatmap.ImageLoader.destroy(ImageLoader.java:171)
	at itdelatrisu.opsu.beatmap.Beatmap$1.eldestRemoved(Beatmap.java:47)
	at itdelatrisu.opsu.beatmap.LRUCache.removeEldestEntry(LRUCache.java:47)
	at java.util.LinkedHashMap.addEntry(LinkedHashMap.java:431)
	at java.util.HashMap.put(HashMap.java:505)
	at itdelatrisu.opsu.beatmap.Beatmap.loadBackground(Beatmap.java:291)
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1401)
	at itdelatrisu.opsu.states.DownloadsMenu$3.run(DownloadsMenu.java:730)
```

**Comment by itdelatrisu** [comment]
Should be fixed now, thanks a lot!
