### ISSUE TITLE
Failed to load file 'C:\Users\netman1221\Desktop\opsu\.\Skins\foo\menuclick.wav'.

### ISSUE THREAD

**Issue by AureoleArk** [itdelatrisu/opsu#160]
**Version:** 0.12.1
**Build date:** 2015-10-02 03:05
**OS:** Windows 8.1 (amd64)
**JRE:** 1.8.0_45
**Error:** `Failed to load file 'C:\Users\netman1221\Desktop\opsu\.\Skins\foo\menuclick.wav'.`
**Stack trace:**

```
java.lang.ArrayIndexOutOfBoundsException: 15
    at javazoom.jl.decoder.LayerIDecoder$SubbandLayer1Stereo.read_allocation(LayerIDecoder.java:396)
    at javazoom.jl.decoder.LayerIDecoder.readAllocation(LayerIDecoder.java:108)
    at javazoom.jl.decoder.LayerIDecoder.decodeFrame(LayerIDecoder.java:72)
    at javazoom.jl.decoder.Decoder.decodeFrame(Decoder.java:147)
    at javazoom.spi.mpeg.sampled.convert.DecodedMpegAudioInputStream.execute(DecodedMpegAudioInputStream.java:185)
    at org.tritonus.share.TCircularBuffer.read(TCircularBuffer.java:138)
    at org.tritonus.share.sampled.convert.TAsynchronousFilteredAudioInputStream.read(TAsynchronousFilteredAudioInputStream.java:197)
    at itdelatrisu.opsu.audio.MultiClip.<init>(MultiClip.java:76)
    at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:169)
    at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:93)
    at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:213)
    at itdelatrisu.opsu.states.Splash$2.run(Splash.java:157)
```

**Comment by itdelatrisu** [comment]
(really late reply, sorry)
Closing since it doesn't look like there's anything we can do here (not worth looking into why JLayer is crashing).
