### ISSUE TITLE
Could not connect to database: '.\.opsu_scores.db'.

### ISSUE THREAD

**Issue by won136** [itdelatrisu/opsu#165]
**Version:** 0.12.1
**Build date:** 2015-10-02 03:05
**OS:** Windows 7 (x86)
**JRE:** 1.8.0_25
**Error:** `Could not connect to database: '.\.opsu_scores.db'.`
**Stack trace:**
```
java.sql.SQLException: opening db: '.\.opsu_scores.db': 액세스가 거부되었습니다
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:203)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
	at itdelatrisu.opsu.db.ScoreDB.init(ScoreDB.java:88)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:47)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:166)
```

**Comment by won136** [comment]
is only my problem? i cant play this game my computer

**Comment by itdelatrisu** [comment]
Did you read the responses to #112?
