### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by won136** [itdelatrisu/opsu#166]
**Version:** 0.12.1
**Build date:** 2015-10-02 03:05
**OS:** Windows 7 (x86)
**JRE:** 1.8.0_25
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.UnsatisfiedLinkError: Can't load library: C:\Windows\system32\.\Natives\lwjgl.dll
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:197)
```

**Comment by itdelatrisu** [comment]
Duplicate/related to #165.
