### ISSUE TITLE
Game.update() failure.

### ISSUE THREAD

**Issue by netman1221** [itdelatrisu/opsu#171]
**Version:** 0.12.1
**Build date:** 2015-10-02 03:05
**OS:** Windows 8.1 (amd64)
**JRE:** 1.8.0_45
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:98)
	at itdelatrisu.opsu.Container.start(Container.java:72)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 15
	at javazoom.jl.decoder.LayerIDecoder$SubbandLayer1Stereo.read_allocation(LayerIDecoder.java:396)
	at javazoom.jl.decoder.LayerIDecoder.readAllocation(LayerIDecoder.java:108)
	at javazoom.jl.decoder.LayerIDecoder.decodeFrame(LayerIDecoder.java:72)
	at javazoom.jl.decoder.Decoder.decodeFrame(Decoder.java:147)
	at org.newdawn.slick.openal.Mp3InputStream.read(Mp3InputStream.java:124)
	at org.newdawn.slick.openal.Mp3InputStream.read(Mp3InputStream.java:154)
	at org.newdawn.slick.openal.Mp3InputStream.read(Mp3InputStream.java:169)
	at org.newdawn.slick.openal.OpenALStreamPlayer.stream(OpenALStreamPlayer.java:305)
	at org.newdawn.slick.openal.OpenALStreamPlayer.startPlayback(OpenALStreamPlayer.java:394)
	at org.newdawn.slick.openal.OpenALStreamPlayer.play(OpenALStreamPlayer.java:230)
	at org.newdawn.slick.openal.StreamSound.playAsMusic(StreamSound.java:46)
	at org.newdawn.slick.Music.startMusic(Music.java:314)
	at org.newdawn.slick.Music.play(Music.java:281)
	at org.newdawn.slick.Music.play(Music.java:271)
	at itdelatrisu.opsu.audio.MusicController.playAt(MusicController.java:163)
	at itdelatrisu.opsu.audio.MusicController.loopTrackIfEnded(MusicController.java:333)
	at itdelatrisu.opsu.states.Song

**Comment by k1nzy** [comment]
Backup your beatmaps/skins then reinstall opsu on https://itdelatrisu.github.io/opsu/ or https://github.com/itdelatrisu/opsu/Releases ill fix the second link if that one doesn't work
