### ISSUE TITLE
Failed to load file /Downloads/./Skins/Girls HD/combobreak.mp3'.

### ISSUE THREAD

**Issue by Darksider3** [itdelatrisu/opsu#174]
Got that every run, anyway which Skin i load.
**Version:** 0.12.1
**Build date:** 2015-10-02 03:05
**OS:** Linux (amd64)
**JRE:** 1.7.0_91
**Error:** `Failed to load file '/home/darksider3/Downloads/./Skins/Girls HD/combobreak.mp3'.`
**Stack trace:**
```
java.lang.IllegalArgumentException: Invalid format
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:142)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:99)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:283)
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:171)
	at itdelatrisu.opsu.audio.MultiClip.<init>(MultiClip.java:97)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:120)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:93)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:213)
	at itdelatrisu.opsu.states.Splash$1.run(Splash.java:129)
```

**Comment by CristianChPuma** [comment]
For some reason there are issues with hitsounds in Linux version. So there's an option to disable them to avoid these problems.

**Comment by Darksider3** [comment]
Funny, while i get sometimes Hitsounds.... Randomly all ~900 Beats whom hitted. Okay, just done. Thanks.

**Comment by Bigpet** [comment]
seems like a duplicate of https://github.com/itdelatrisu/opsu/issues/89

**Comment by Darksider3** [comment]
Hrm, #89 is assuming that the file is given in WAV. Here we have mp3. But possible, yeah.

**Comment by Bigpet** [comment]
@Darksider3 it doesn't matter if it's wav or mp3 it's about the sampling rate and quantization
