### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by mikekamrath** [itdelatrisu/opsu#181]
**Version:** 0.12.1
**Build date:** 2016-03-22 22:44
**OS:** Linux (amd64)
**JRE:** 1.7.0_95
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.ExceptionInInitializerError
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:197)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 4 more
```

**Comment by SajeOne** [comment]
Getting the same exception

**Comment by SajeOne** [comment]
I found a solution to the problem, I didn't have the package 'xorg-xrandr' installed on Arch Linux. I guess the LWJGL library uses it to find the available monitors.
