### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by Alquimerico** [itdelatrisu/opsu#185]
**Version:** 0.12.1
**Build date:** 2015-10-02 03:05
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_91
**Error:** `** Uncaught Exception! **`
**Stack trace:**

```
java.lang.NullPointerException
    at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
    at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
    at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
    at itdelatrisu.opsu.Container.close_sub(Container.java:121)
    at itdelatrisu.opsu.Container.start(Container.java:75)
    at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
```

**Comment by itdelatrisu** [comment]
Cleaning out old issues related to #218, please open another issue if this happens again. Thanks!
