### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by ZenouReimu** [itdelatrisu/opsu#187]
**Version:** 0.12.1
**Build date:** 2016-06-17 19:28
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_65
**Error:** `** Uncaught Exception! **`
**Stack trace:**

```
java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Reimu\Desktop\itdelatrisu-opsu-93c8ab9\.\Natives\lwjgl64.dll
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at org.lwjgl.Sys$1.run(Sys.java:70)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
    at org.lwjgl.Sys.loadLibrary(Sys.java:87)
    at org.lwjgl.Sys.<clinit>(Sys.java:117)
    at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
    at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
    at itdelatrisu.opsu.Opsu.main(Opsu.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by iceblade112** [comment]
You need the LWJGL natives in the `Natives\` folder for your platform, so win64 I guess.
