### ISSUE TITLE
UnsatisfiedLinkError with SQLite on ArchLinux

### ISSUE THREAD

**Issue by Zeg9** [itdelatrisu/opsu#19]
Here is what I get on ArchLinux with sqlite 3.8.8 (tried 3.8.7 as well, same error):
```
** Uncaught Exception! **
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
	at org.sqlite.core.NativeDB._open(Native Method)
	at org.sqlite.core.DB.open(DB.java:161)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:145)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at itdelatrisu.opsu.ScoreDB.init(ScoreDB.java:63)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:145)
```
I tried installing some "javasqlite" package, as well as switching to java 8 - with no effect.

**Comment by itdelatrisu** [comment]
Any luck if you use 3.8.6?

**Comment by Zeg9** [comment]
Same error :|

**Comment by fluddokt** [comment]
https://github.com/fluddokt/opsu/releases/download/0.5.0sqlite386/opsu-0.5.0-sqlite386.jar
try this?

**Comment by Zeg9** [comment]
@fluddokt this one works, whatever sqlite version I have on system (I don't even think it matters actually)

**Comment by fluddokt** [comment]
https://bitbucket.org/xerial/sqlite-jdbc/issue/152/387-version-linux-issue
seems sqlite-jdbc-3.8.7.jar is missing some files

**Comment by Zeg9** [comment]
Ow I see. Not really an issue with the game itself then :x
Should I close this ?

**Comment by itdelatrisu** [comment]
Will be fixed by the next release, or compile the source yourself.  Thanks!
