### ISSUE TITLE
Cannot run opsu! at all [Win10]

### ISSUE THREAD

**Issue by JapanYoshi** [itdelatrisu/opsu#191]
I get this heap of errors whenever I run Windows 10, and I can't find anyone else who had the same issue.

```
Sun Jul 31 21:29:50 JST 2016 ERROR:Could not connect to database: '.\.opsu.db'.
Sun Jul 31 21:29:50 JST 2016 ERROR:Error opening connection
java.sql.SQLException: Error opening connection
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:215)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:74)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:46)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:166)
Caused by: java.lang.NullPointerException
	at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:169)
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:290)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65)
	at org.sqlite.core.NativeDB.load(NativeDB.java:53)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:211)
	... 12 more
Sun Jul 31 21:29:55 JST 2016 ERROR:Could not connect to database: '.\.opsu_scores.db'.
Sun Jul 31 21:29:55 JST 2016 ERROR:Error opening connection
java.sql.SQLException: Error opening connection
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:215)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
	at itdelatrisu.opsu.db.ScoreDB.init(ScoreDB.java:88)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:47)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:166)
Caused by: java.lang.NullPointerException
	at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:169)
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:290)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65)
	at org.sqlite.core.NativeDB.load(NativeDB.java:53)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:211)
	... 12 more
Sun Jul 31 21:29:56 JST 2016 ERROR:** Uncaught Exception! **
Sun Jul 31 21:29:56 JST 2016 ERROR:Resource not found: version
java.lang.RuntimeException: Resource not found: version
	at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69)
	at itdelatrisu.opsu.downloads.Updater.checkForUpdates(Updater.java:207)
	at itdelatrisu.opsu.Opsu$2.run(Opsu.java:181)
Sun Jul 31 21:29:56 JST 2016 ERROR:Resource not found: icon16.png
java.lang.RuntimeException: Resource not found: icon16.png
	at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69)
	at org.newdawn.slick.AppGameContainer.setIcons(AppGameContainer.java:527)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:202)
Sun Jul 31 21:29:56 JST 2016 ERROR:JARs cannot be run from some paths containing '!'. Please move or rename the file and try again.
```

**Comment by Bigpet** [comment]
I think the error message `ERROR:JARs cannot be run from some paths containing '!'. Please move or rename the file and try again.` speaks for itself

**Comment by wacossusca34** [comment]
This is a very old JRE-wide bug: http://bugs.java.com/view_bug.do?bug_id=4523159, which has been neglected due to the requirement of having to change the java specification using `!/`. As a result, it's best to avoid the use of '!' in _the end of a file/directory name_ of any paths fed to a Java program that might be used for `java.net.URL` using a `jar:` path.
