### ISSUE TITLE
Failed to create JSON array when searching for songs on Hexide.

### ISSUE THREAD

**Issue by bngs** [itdelatrisu/opsu#192]
**Version:** 0.12.1
**Build date:** 2016-08-12 10:07
**OS:** Linux (amd64)
**JRE:** 1.7.0_111
**Error:** `Failed to create JSON array.`
**Stack trace:**
```
org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONArray.<init>(JSONArray.java:105)
	at org.json.JSONArray.<init>(JSONArray.java:144)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:430)
	at itdelatrisu.opsu.downloads.servers.HexideServer.resultList(HexideServer.java:84)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:213)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by iceblade112** [comment]
Hexide is broken.

`Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

**Comment by itdelatrisu** [comment]
Thanks for letting me know; it's a Hexide problem, though newer opsu! builds (not yet released, but you can build from source) shouldn't throw an error.

Will keep HexideServer in the code for now since https://osu.hexide.com/list/ seems to be online and maybe the API will get fixed.
