### ISSUE TITLE
Failed to create JSON array.

### ISSUE THREAD

**Issue by Menci** [itdelatrisu/opsu#194]
**Version:** 0.12.1
**Build date:** 2016-08-27 13:32
**OS:** Linux (amd64)
**JRE:** 1.8.0_91
**Error:** `Failed to create JSON array.`
**Stack trace:**
```
org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONArray.<init>(JSONArray.java:105)
	at org.json.JSONArray.<init>(JSONArray.java:144)
	at itdelatrisu.opsu.Utils.readJsonArrayFromUrl(Utils.java:430)
	at itdelatrisu.opsu.downloads.servers.HexideServer.resultList(HexideServer.java:84)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:213)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by iceblade112** [comment]
#192?
