### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by Alcaida** [itdelatrisu/opsu#196]
**Version:** 0.12.1
**Build date:** 2016-10-01 17:26
**OS:** Windows 8.1 (amd64)
**JRE:** 1.8.0_74
**Error:** `** Uncaught Exception! **`
**Stack trace:**

```
java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalDeleteSources(IJ)V
    at org.lwjgl.openal.AL10.nalDeleteSources(Native Method)
    at org.lwjgl.openal.AL10.alDeleteSources(AL10.java:766)
    at itdelatrisu.opsu.audio.MusicController.destroyOpenAL(MusicController.java:445)
    at itdelatrisu.opsu.audio.MusicController.reset(MusicController.java:410)
    at itdelatrisu.opsu.Container.close_sub(Container.java:124)
    at itdelatrisu.opsu.Container.start(Container.java:67)
    at itdelatrisu.opsu.Opsu.main(Opsu.java:204)
```

**Comment by itdelatrisu** [comment]
Any details about when this happened, what you were doing, or how frequently this occurs?  (If it's rare, it's probably just an LWJGL bug; restart and it'll be fixed.)
