### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by matthewechavez1** [itdelatrisu/opsu#200]
**Version:** 0.12.1
**Build date:** 2016-10-10 21:19
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_102
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
	at itdelatrisu.opsu.Container.close_sub(Container.java:121)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:204)
```

**Comment by itdelatrisu** [comment]
Is there anything else in your logs?  (There should be a file `.opsu.log` in the same directory.)

**Comment by matthewechavez1** [comment]
It's ok now, i solved it by using an old version of Java (7u80 to be exact). It probably hates my GPU

https://puu.sh/rSh5J/e4db271be7.png
