### ISSUE TITLE
Failed to create JSON object.

### ISSUE THREAD

**Issue by ShyPixie** [itdelatrisu/opsu#201]
**Version:** 0.8.0
**Build date:** 2015-05-14 20:07
**OS:** Linux (amd64)
**JRE:** 1.8.0_102
**Error:** `Failed to create JSON object.`
**Stack trace:**
```
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at itdelatrisu.opsu.Utils.readJsonFromUrl(Utils.java:570)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:67)
	at itdelatrisu.opsu.states.DownloadsMenu$1.run(DownloadsMenu.java:408)
```

**Comment by Lemmmy** [comment]
use a different beatmap mirror

**Comment by itdelatrisu** [comment]
Please update to the latest version, opsu! 0.8.0 uses an old API.
