### ISSUE TITLE
Port Changeing not working

### ISSUE THREAD

**Issue by Swimgiant** [itdelatrisu/opsu#202]
I change the port when I get the error message to and it does nothing except change the port listed on the window Please Help

**Comment by Swimgiant** [comment]
here is the full code 

Wed Oct 12 22:03:29 CDT 2016 ERROR:Another program is already running on port 49250.
Wed Oct 12 22:03:29 CDT 2016 ERROR:Unrecognized Windows Sockets error: 10107: create
java.net.SocketException: Unrecognized Windows Sockets error: 10107: create
	at java.net.ServerSocket.createImpl(Unknown Source)
	at java.net.ServerSocket.getImpl(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:119)

**Comment by Swimgiant** [comment]
tried a different port and I got this 

Failed to write to file 'C:\WINDOWS\system32\.\.opsu.cfg'.
java.io.FileNotFoundException: .\.opsu.cfg (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at itdelatrisu.opsu.Options.saveOptions(Options.java:1077)
	at itdelatrisu.opsu.Options.parseOptions(Options.java:897)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:115)

**Comment by itdelatrisu** [comment]
That's probably because you're running the jar from system32...
