### ISSUE TITLE
Could not connect to database: '.\.opsu.db'.

### ISSUE THREAD

**Issue by Beafantles** [itdelatrisu/opsu#213]
**Version:** 0.12.1
**Build date:** 2015-10-02 03:05
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_111
**Error:** `Could not connect to database: '.\.opsu.db'.`
**Stack trace:**
```
java.sql.SQLException: opening db: '.\.opsu.db': Accès refusé <-- It means "Unauthorized access" in english
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:203)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:74)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:46)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:166)
```

**Comment by Lemmmy** [comment]
Make sure there is no `!` anywhere in the path at opsu! is saved. There cannot be a `!` character anywhere in the file path, or the game will not run.

If that doesn't fix it, make sure the `.opsu.db` file isn't marked as "read only", and that your user has permissions to write to it.

**Comment by itdelatrisu** [comment]
This might be fixed in the latest version if the jar was getting launched from system32.  If not (and also not anything from the post above), feel free to comment with more details.
