### ISSUE TITLE
Could not start a clip 'soft-slidertick.wav'.

### ISSUE THREAD

**Issue by polarkac** [itdelatrisu/opsu#226]
**Version:** 0.13.0
**Build date:** 2017-01-04 10:09
**OS:** Linux (amd64)
**JRE:** 1.8.0_112
**OpenGL Version:** 4.5.0 NVIDIA 375.26 (NVIDIA Corporation)
**Error:** `Could not start a clip 'soft-slidertick.wav'.`
**Stack trace:**
```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1052)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:189)
	at itdelatrisu.opsu.audio.MultiClip.start(MultiClip.java:133)
	at itdelatrisu.opsu.audio.SoundController.playClip(SoundController.java:272)
	at itdelatrisu.opsu.audio.SoundController.playHitSound(SoundController.java:323)
	at itdelatrisu.opsu.GameData.sendSliderTickResult(GameData.java:1277)
	at itdelatrisu.opsu.objects.Slider.update(Slider.java:656)
	at itdelatrisu.opsu.states.Game.updateGame(Game.java:987)
	at itdelatrisu.opsu.states.Game.runReplayFrame(Game.java:1913)
	at itdelatrisu.opsu.states.Game.addReplayFrameAndRun(Game.java:1896)
	at itdelatrisu.opsu.states.Game.update(Game.java:778)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:266)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:109)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:209)
```

**Comment by mad-s** [comment]
What distro are you using? Are you using pulseaudio, ALSA or JACK? Can you post your `/usr/lib/jvm/default-java/jre/lib/sound.properties`?

**Comment by polarkac** [comment]
I am using Archlinux with PulseAudio (9.0-1)


```
/usr/lib/jvm/default-runtime/lib/sound.properties

############################################################
#               Sound Configuration File
############################################################
#
# This properties file is used to specify default service
# providers for javax.sound.midi.MidiSystem and
# javax.sound.sampled.AudioSystem.
#
# The following keys are recognized by MidiSystem methods:
#
# javax.sound.midi.Receiver
# javax.sound.midi.Sequencer
# javax.sound.midi.Synthesizer
# javax.sound.midi.Transmitter
#
# The following keys are recognized by AudioSystem methods:
#
# javax.sound.sampled.Clip
# javax.sound.sampled.Port
# javax.sound.sampled.SourceDataLine
# javax.sound.sampled.TargetDataLine
#
# The values specify the full class name of the service
# provider, or the device name.
#
# See the class descriptions for details.
#
# Example 1:
# Use MyDeviceProvider as default for SourceDataLines:
# javax.sound.sampled.SourceDataLine=com.xyz.MyDeviceProvider
#
# Example 2:
# Specify the default Synthesizer by its name "InternalSynth".
# javax.sound.midi.Synthesizer=#InternalSynth
#
# Example 3:
# Specify the default Receiver by provider and name:
# javax.sound.midi.Receiver=com.sun.media.sound.MidiProvider#SunMIDI1
#
```

**Comment by mad-s** [comment]
What happens if you add these lines to that file:
```
javax.sound.sampled.Clip=org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider
javax.sound.sampled.Port=org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider
javax.sound.sampled.SourceDataLine=org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider
javax.sound.sampled.TargetDataLine=org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider
```
(You probably need icedtea-web installed)

**Comment by polarkac** [comment]
It completely crashed with empty Error window. I had to kill it.

https://www.dropbox.com/s/8rj8ptvdnbpsqdx/040117-103955.jpg?dl=0

**Comment by mad-s** [comment]
Wait, so the music plays fine? What sample rate does `pacmd list-sinks` report?
Does your sound card support resampling? Did you build with gradle or maven?

**Comment by polarkac** [comment]
Sorry I should better describe the problem. I can play any beatmap but mostly after a spinner it starts to throw exceptions.

```
$ pacmd list-sinks

  * index: 0
	name: <alsa_output.pci-0000_00_1b.0.analog-stereo>
	driver: <module-alsa-card.c>
	flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: RUNNING
	suspend cause: 
	priority: 9959
	volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	base volume: 65536 / 100% / 0.00 dB
	volume steps: 65537
	muted: no
	current latency: 16.41 ms
	max request: 4 KiB
	max rewind: 375 KiB
	monitor source: 1
	sample spec: s16le 2ch 48000Hz
	channel map: front-left,front-right
	             Stereo
	used by: 1
	linked by: 3
	configured latency: 21.33 ms; range is 0.50 .. 2000.00 ms
	card: 2 <alsa_card.pci-0000_00_1b.0>
	module: 8
	properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "ALC892 Analog"
		alsa.id = "ALC892 Analog"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "0"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xf6110000 irq 29"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1b.0"
		sysfs.path = "/devices/pci0000:00/0000:00:1b.0/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "1e20"
		device.product.name = "7 Series/C216 Chipset Family High Definition Audio Controller"
		device.form_factor = "internal"
		device.string = "front:0"
		device.buffering.buffer_size = "384000"
		device.buffering.fragment_size = "192000"
		device.access_mode = "mmap+timer"
		device.profile.name = "analog-stereo"
		device.profile.description = "Analog Stereo"
		device.description = "Built-in Audio Analog Stereo"
		alsa.mixer_name = "Realtek ALC892"
		alsa.components = "HDA:10ec0892,1462d758,00100302"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	ports:
		analog-output-lineout: Line Out (priority 9900, latency offset 0 usec, available: yes)
			properties:
				
		analog-output-headphones: Headphones (priority 9000, latency offset 0 usec, available: no)
			properties:
				device.icon_name = "audio-headphones"
	active port: <analog-output-lineout>
```

Its build with Gradle from AUR (https://aur.archlinux.org/packages/opsu/).

I just restarted computer and it seems fine. I usually suspend computer over night, maybe that was the reason for the exceptions?

**Comment by mad-s** [comment]
Your sound card is configured to 48000Hz sample rate, while the sound effects are 44100Hz. Normally, the sound engine would resample, but for some reason that didn't happen. What's the output of `pulseaudio --dump-resample-methods`?

**Comment by polarkac** [comment]
```
$ pulseaudio --dump-resample-methods

trivial
speex-float-0
speex-float-1
speex-float-2
speex-float-3
speex-float-4
speex-float-5
speex-float-6
speex-float-7
speex-float-8
speex-float-9
speex-float-10
speex-fixed-0
speex-fixed-1
speex-fixed-2
speex-fixed-3
speex-fixed-4
speex-fixed-5
speex-fixed-6
speex-fixed-7
speex-fixed-8
speex-fixed-9
speex-fixed-10
ffmpeg
auto
copy
peaks
soxr-mq
soxr-hq
soxr-vhq
```

**Comment by polarkac** [comment]
I just noticed in Pavucontrol, when Sound Effects are all enabled, it creates insanly many streams (Alsa plugin [java]).

Tried also latest version from git and its still not fixed.

**Comment by tpenguinltg** [comment]
All those streams seem to be a side effect of using Java's `AudioSystem`. There's one stream per sound clip loaded. This [StackOverflow post](https://stackoverflow.com/questions/7112879/java-clip-sound-echoing-and-not-playing-efficiantly) suggests that using `SourceDataLine` instead of `DataLine` might help with longer clips.

**Comment by GigabyteProductions** [comment]
With the exception line reading:
```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
```
my `pacmd list-sinks` output shows that this is exactly what I'm playing at:
```
sample spec: s16le 2ch 44100Hz
```
In fact, this is the format that most of my beatmaps/hitsounds are in:
```
$ find Songs | grep -i '\.\(wav\|mp3\)$' | head | while read file; do file "$file"; done
Songs/158023 UNDEAD CORPORATION - Everything will freeze/12 - Everything will freeze.mp3: MPEG ADTS, layer III, v1, 192 kbps, 44.1 kHz, Stereo
Songs/158023 UNDEAD CORPORATION - Everything will freeze/normal-hitclap.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz
Songs/262403 AKI AKANE - Kando_Reduction/soft-hitfinish.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz
Songs/262403 AKI AKANE - Kando_Reduction/normal-hitclap80.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz
Songs/262403 AKI AKANE - Kando_Reduction/normal-slidertick80.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz
Songs/262403 AKI AKANE - Kando_Reduction/soft-hitwhistle.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz
Songs/262403 AKI AKANE - Kando_Reduction/normal-sliderslide80.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz
Songs/262403 AKI AKANE - Kando_Reduction/normal-hitclap50.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz
Songs/262403 AKI AKANE - Kando_Reduction/Reduction.mp3: Audio file with ID3 version 2.4.0, contains: MPEG ADTS, layer III, v1, 192 kbps, 44.1 kHz, Stereo
Songs/262403 AKI AKANE - Kando_Reduction/soft-sliderslide.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz
```
I'm wondering if the issue is closer to [this](https://stackoverflow.com/questions/11915469/java-sound-format-not-supported/12029800#12029800).

For reproduction, the Exception is thrown many times starting at approximately 60% through [513590 - RADWIMPS - Zen Zen Zense (movie ver.)](https://osu.ppy.sh/s/513590) on Habi's Insane

**Comment by GigabyteProductions** [comment]
Well, I've noticed that this is not reproducible on my laptop, so I updated the kernel on both (the only pacakge that didn't match), I've managed to both:
1. Not be able to reproduce on my desktop (where I originally observed the issue)
2. Not be able to go above 5 fps, even when booted into the original kernel (I almost want to blame nouveau, but am not sure)

Considering the (un)reproducibility issue, I may not be able to contribute more to the issue.

**Comment by GigabyteProductions** [comment]
It appears that doing upgrades of all packages fixed the 5 fps issue, but I am still unable to reproduce the Exception. It's possible that this was a bug in the sound system, but I think it's worth considering whether this might be a concurrency issue (but only exposed under certain (random?) conditions), as described in the StackOverflow link.

**Comment by GigabyteProductions** [comment]
With many days of uptime, nouveau becomes inconsistent with my graphics card, and the issue is reproducing again. With this, I stand by my theory that certain load conditions may be triggering a concurrency issue in the sound system.

**Comment by GigabyteProductions** [comment]
I have identified the "certain conditions" that triggers the issue on my systems. I didn't realize that when I was not producing the issue, I did not have Mumble open (I usually have it open). Opening Mumble makes the issue reproducible again. The implication of this is that Mumble's echo cancellation causes it to constantly monitor the output of the default PulseAudio sink. When combined with the fact that opsu! opens new connections to PulseAudio for every hitsound, I believe the result is a high load that causes delays in new connections (and thus concurrency issues for the Java Objects).

To test my theory, I have eliminated nearly all other variables in my PulseAudio environment. With opsu! (now at 0.15.0) being the only playback, I recreate the output-monitoring load by spawning many of `PULSE_SOURCE="$(pactl info | sed -ne 's/^Default Sink: \(\S\+\)$/\1/p').monitor" pacat -r > /dev/null`, and I eliminate hardware backends by only having one null output sink. The PulseAudio daemon is configured with the following ~/.config/pulse/default.pa daemon script:
```
load-module module-native-protocol-unix
load-module module-null-sink
load-module module-suspend-on-idle
```
Restarting the PulseAudio daemon is necessary for this configuration change to take effect. This can be done with `pactl exit`

The results of my test are hit-and-miss pretty early on, but a trend is evident that with the more `pacat` processes I spawn, the earler the issue appears in the song I am testing with. The summary of the trend progression on my desktop is as follows:

`pacat` processes | results observed
-- | --
5 | Hit and miss: reproducing at the same 60% progress of test beatmap
10 | Reproducing reliably, and at earlier beats
23 | Reproducing on first beat
24 | Hit and miss: "Looks like sound isn't working" on start of game (`AL lib: (EE) alsa_open_playback: Could not open playback device 'default': Connection refused`)
27 | Reproducing on loading of sounds (when game starts)

I am not sure how far into the test this started, but I did notice delays and grouping of hitsound playback. I believe this reinforces my theory that the high load is causing connection delays.

The last two rows are the most interesting results. The "Connection refused" error generally doesn't appear to affect other PulseAudio clients; I am able to open the song with VLC, and spam new connections to PulseAudio by holding "n" (next track), without any issue. I was, however, able to produce "Connection refused" errors when spawning `pacat` processes from a loop without a delay in-between runs of the command.

I have also tested the 27 processes on my laptop (which has *never* produced the original issue before), and am reproducing the result in that row.

**Comment by Lemmmy** [comment]
I can confirm te same issue occurs with Teamspeak.

**Comment by polarkac** [comment]
I dont think that Mumble or Teamspeak is the problem (echo cancelation). I have echo cancelation disabled and it still throws this exception.

In my opinion problem is with many processes (audio streams). HitSound should use OpenAL as well instead of Javax Sound.

**Comment by GigabyteProductions** [comment]
I agree. I did not think Mumble was the problem, but only exposed opsu!/Java's problem.

**Comment by itdelatrisu** [comment]
Hit sounds were originally (years ago) played through OpenAL, but at least on Windows there was significantly higher latency (e.g. from when you call play() to when the sound actually plays) with OpenAL compared with JavaSound, which is why I switched in the first place.  Not sure how to proceed with this. :/

**Comment by tpenguinltg** [comment]
If OpenAL works better on Linux but Java Sound elsewhere, perhaps an OS check and a user option? Abstract the play function for OpenAL and Java Sound into an interface and swap out the driver based on the OS/option.

**Comment by GigabyteProductions** [comment]
As far as I understand, software mixing is usually done on the client side before sending it to OS's sound system. opsu! can mix it, and stream it to PulseAudio with one connection. There will be less dependencies (if this can work with Java's sound system), and behavior is more consistent across platforms.

This doesn't imply that an audio library cannot do the mixing, but I guess OpenAL (or it's Java binding?) is too "slow" for a rhythm game.

**Comment by Lemmmy** [comment]
Why not give BASS a go? Lig and I used it for our osu! clone and it worked brilliantly.

**Comment by tpenguinltg** [comment]
"free for non-commercial use" is [incompatible with the GPLv3](https://softwareengineering.stackexchange.com/questions/214904/is-free-for-non-commercial-use-license-compatible-with-gnu-gplv3-license), so BASS is unfortunately not an option.

**Comment by Lemmmy** [comment]
rip

**Comment by tpenguinltg** [comment]
I'm still a little confused as to how this works and how to use it, but perhaps Java's [Mixer](https://docs.oracle.com/javase/tutorial/sound/sampled-overview.html) is what we're looking for? It supports handling any number of input streams and any number of output streams, so we can feed the sound clips as input and expose just one stream to the system.

**Comment by tpenguinltg** [comment]
I'm starting to suspect that these "Could not start clip" issues are because of a limit on open lines.

https://github.com/ddf/Minim/issues/45#issuecomment-138742677

A possible solution is mentioned in the comments following, and another is in the original post.
