### ISSUE TITLE
Could not start a clip 'spinnerbonus.wav'.

### ISSUE THREAD

**Issue by polarkac** [itdelatrisu/opsu#227]
**Version:** 0.13.0
**Build date:** 2017-01-04 10:09
**OS:** Linux (amd64)
**JRE:** 1.8.0_112
**OpenGL Version:** 4.5.0 NVIDIA 375.26 (NVIDIA Corporation)
**Error:** `Could not start a clip 'spinnerbonus.wav'.`
**Stack trace:**
```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1052)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:189)
	at itdelatrisu.opsu.audio.MultiClip.start(MultiClip.java:133)
	at itdelatrisu.opsu.audio.SoundController.playClip(SoundController.java:272)
	at itdelatrisu.opsu.audio.SoundController.playSound(SoundController.java:284)
	at itdelatrisu.opsu.objects.Spinner.rotate(Spinner.java:386)
	at itdelatrisu.opsu.objects.Spinner.update(Spinner.java:338)
	at itdelatrisu.opsu.states.Game.updateGame(Game.java:987)
	at itdelatrisu.opsu.states.Game.runReplayFrame(Game.java:1913)
	at itdelatrisu.opsu.states.Game.addReplayFrameAndRun(Game.java:1896)
	at itdelatrisu.opsu.states.Game.update(Game.java:778)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:266)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:109)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:209)
```

**Comment by itdelatrisu** [comment]
Linking to @226.
