### ISSUE TITLE
Failed to load file 'C:\Users\Anyone\AppData\Local\osu!\Skins\Phaze1.6\soft-slidertick.wav'.

### ISSUE THREAD

**Issue by iNitroPlays** [itdelatrisu/opsu#229]
**Version:** 0.13.0
**Build date:** 2016-12-27 05:03
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_92
**OpenGL Version:** 4.4.0 - Build 20.19.15.4352 (Intel)
**Error:** `Failed to load file 'C:\Users\Anyone\AppData\Local\osu!\Skins\Phaze1.6\soft-slidertick.wav'.`
**Stack trace:**
```
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:95)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:235)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:157)
```

**Comment by itdelatrisu** [comment]
Linking to #230.
