### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by HYP3RD34TH** [itdelatrisu/opsu#235]
**Version:** 0.14.0
**Build date:** 2017-01-09 07:37
**OS:** Linux (amd64)
**JRE:** 9-ea
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static java.lang.String[] java.lang.ClassLoader.sys_paths accessible: module java.base does not "opens java.lang" to unnamed module @28ac3dc3
	at java.base/jdk.internal.reflect.Reflection.throwInaccessibleObjectException(Reflection.java:427)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:201)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:171)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:165)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:162)
```

**Comment by yugecin** [comment]
If you still have jre 1.8, use that version to run opsu.
Otherwise, you can try running from commandline: `java --add-opens java.base/java.lang=ALL-UNNAMED -jar opsu.jar`

**Comment by itdelatrisu** [comment]
(I don't have any plans to fix this until Java 9 is actually released.)

**Comment by HYP3RD34TH** [comment]
JRE 1.8 did the Trick..
