### ISSUE TITLE
Unable to run 0.6.0

### ISSUE THREAD

**Issue by TheOmyNomy** [itdelatrisu/opsu#24]
Sun Feb 22 18:10:07 AEDT 2015 ERROR:Could not connect to score database.
Sun Feb 22 18:10:07 AEDT 2015 ERROR:Error opening connection
java.sql.SQLException: Error opening connection
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:140)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.ScoreDB.init(ScoreDB.java:66)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:136)
Caused by: java.lang.NullPointerException
	at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:165)
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:249)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65)
	at org.sqlite.core.NativeDB.load(NativeDB.java:53)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:136)
	... 10 more
Sun Feb 22 18:10:15 AEDT 2015 ERROR:** Uncaught Exception! **
Sun Feb 22 18:10:15 AEDT 2015 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.ScoreDB.createDatabase(ScoreDB.java:107)
	at itdelatrisu.opsu.ScoreDB.init(ScoreDB.java:73)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:136)

**Comment by TheOmyNomy** [comment]
**Update**: I've moved opsu.jar from the my secondary hard drive to my primary hard drive and it miraculously runs. Maybe it has issues communicating over hard drives?

**Comment by itdelatrisu** [comment]
Ugh, I don't know why there are so many problems with the SQLite JDBC releases.  The only thing I can suggest is trying different versions.  The current one is 3.8.6.  Does opsu-0.5.0 work (sqlite-jdbc-3.8.7)?  Or try sqlite-jdbc-3.7.2?  (Do you need me to compile binaries for you?)

**Comment by TheOmyNomy** [comment]
I get the same problem with 0.5.0 as well. And yes I would like you to compiles the binaries for me thanks.

**Comment by itdelatrisu** [comment]
Here's using sqlite-jdbc-3.7.2: http://www.mediafire.com/download/ozajcvvqu3wm1m8/opsu-0.6.0-runnable.jar

**Comment by TheOmyNomy** [comment]
Mon Feb 23 16:56:12 AEDT 2015 ERROR:Unable to determine Slick build number
Mon Feb 23 16:56:12 AEDT 2015 ERROR:Resource not found: icon16.png
java.lang.RuntimeException: Resource not found: icon16.png
	at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69)
	at org.newdawn.slick.AppGameContainer.setIcons(AppGameContainer.java:527)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:148)
Mon Feb 23 16:56:12 AEDT 2015 ERROR:Cannot run JAR from path containing '!'.

I get this error when attempting to run opsu-0.6.0-runnable.jar

**Comment by itdelatrisu** [comment]
Try moving it somewhere else (as the exception says, a path without '!').  It's a known Java bug that hasn't been fixed for a decade.

**Comment by TheOmyNomy** [comment]
I've changed the location to somewhere without "!" and it runs now (still running opsu-0.6.0-runnable.jar off the secondary hard drive as well).

I also tried the regular opsu-0.6.0.jar and that works as well now... looks as if that "!" java bug was the cause...

Thanks for the assistance! :+1:
