### ISSUE TITLE
Failed to initialise the LWJGL display

### ISSUE THREAD

**Issue by iamale** [itdelatrisu/opsu#248]
I have [updated](https://github.com/itdelatrisu/opsu/issues/245#issuecomment-276960318), and a new exception occurs now:

---

**Version:** 0.14.0
**Build date:** 2017-01-09 07:37
**OS:** Linux (amd64)
**JRE:** 1.7.0_121
**Stack trace:**
```
org.newdawn.slick.SlickException: Failed to initialise the LWJGL display
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:378)
	at itdelatrisu.opsu.Container.start(Container.java:72)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
```

**Comment by itdelatrisu** [comment]
What happens if you add `-Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true`?  i.e.
```
java -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true -jar opsu-0.14.0.jar
```

**Comment by itdelatrisu** [comment]
If that's the issue, might be resolved in f4a37d7.  (Not able to test this, though.)

**Comment by iamale** [comment]
`-Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true` didn't resolve it, still the same exception. I can still build and test from `master` (or https://github.com/itdelatrisu/opsu/commit/f4a37d7d5415848b2c78dfb8d6fec096777671a6) this weekend.

And [here](https://gist.github.com/iamale/27631da0b88527df2fd3ced35f5352c5) is a copy of (the relevant part of) .opsu.log, just in case.

**Comment by itdelatrisu** [comment]
Well, no ideas on my end, then.  (No need to build from that commit, it just adds the same flag during runtime.)

Found something that might be related, but it's 8 years old and probably irrelevant now: http://slick.ninjacave.com/forum/viewtopic.php?t=1674
