### ISSUE TITLE
Failure at song end causes NullPointerException

### ISSUE THREAD

**Issue by tpenguinltg** [itdelatrisu/opsu#249]
I somehow managed to drain my health in such a way that, just as the final item of the map, a spinner, finished (or almost finished), my health drained completely and it registered as a fail. Attempting to retry caused the sound to distort as it normally would for a fail and all objects to slow down significantly. I pressed Escape and Retry in an attempt to reset the map, then the NullPointerException appeared and opsu! crashed.

Map: https://osu.ppy.sh/s/293233

**Version:** 0.14.0
**Build date:** 2017-02-03 22:01
**OS:** Linux (amd64)
**JRE:** 1.8.0_121
**OpenGL version:** 3.0 Mesa 13.0.3 (Intel Open Source Technology Center)
**Stack trace:**
```
java.lang.NullPointerException
	at org.newdawn.slick.openal.SoundStore.setMusicPitch(SoundStore.java:539)
	at org.newdawn.slick.Music.setPitch(Music.java:397)
	at itdelatrisu.opsu.audio.MusicController.setPitch(MusicController.java:447)
	at itdelatrisu.opsu.states.GamePauseMenu.mousePressed(GamePauseMenu.java:179)
	at org.newdawn.slick.state.StateBasedGame.mousePressed(StateBasedGame.java:499)
	at org.newdawn.slick.Input.poll(Input.java:1241)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:135)
	at itdelatrisu.opsu.Container.start(Container.java:79)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:216)
```

**Comment by itdelatrisu** [comment]
Thanks for catching this.  Turns out it was a bug in Slick2D where the fade-out timers in `Music.java` weren't being reset (ever), so if you call `fade(x, ...)` and the track ends before x, then call `play()`, the "fade" continues in an inconsistent state and bad things start to happen.
