### ISSUE TITLE
Game.render() failure.

### ISSUE THREAD

**Issue by ATAGzh** [itdelatrisu/opsu#253]
**Version:** 0.15.0
**Build date:** 2017-02-05 00:04
**OS:** Windows 7 (x86)
**JRE:** 1.8.0_121
**OpenGL version:** 3.1.0 - Build 9.17.10.4229 (Intel)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:135)
	at itdelatrisu.opsu.Container.start(Container.java:79)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:216)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at itdelatrisu.opsu.ui.NotificationManager.drawNotifications(NotificationManager.java:270)
	at itdelatrisu.opsu.ui.NotificationManager.draw(NotificationManager.java:260)
	at itdelatrisu.opsu.ui.UI.draw(UI.java:124)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:537)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```

**Comment by itdelatrisu** [comment]
Thanks for the report, will be fixed in the next release. :)
