### ISSUE TITLE
No OpenAL Detected

### ISSUE THREAD

**Issue by cscp** [itdelatrisu/opsu#257]
Tue Feb 07 12:45:22 CET 2017 ERROR:Sound initialisation failure.
Tue Feb 07 12:45:22 CET 2017 ERROR:Could not locate OpenAL library.
org.lwjgl.LWJGLException: Could not locate OpenAL library.
	at org.lwjgl.openal.AL.create(AL.java:156)
	at org.lwjgl.openal.AL.create(AL.java:102)
	at org.lwjgl.openal.AL.create(AL.java:206)
	at org.newdawn.slick.openal.SoundStore$1.run(SoundStore.java:325)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.openal.SoundStore.init(SoundStore.java:321)
	at org.newdawn.slick.Music.<init>(Music.java:204)
	at itdelatrisu.opsu.audio.MusicController.loadTrack(MusicController.java:144)
	at itdelatrisu.opsu.audio.MusicController.access$000(MusicController.java:54)
	at itdelatrisu.opsu.audio.MusicController$1.run(MusicController.java:116)
Tue Feb 07 12:45:32 CET 2017 ERROR:Game.update() failure.
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:135)
	at itdelatrisu.opsu.Container.start(Container.java:79)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:216)
Caused by: java.lang.NullPointerException
	at itdelatrisu.opsu.audio.MusicController.setPitch(MusicController.java:447)
	at itdelatrisu.opsu.states.Game.enter(Game.java:1592)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	... 3 more

**Comment by itdelatrisu** [comment]
How often does this happen?  If it's rare, it's a known issue with LWJGL that I can't fix.  I fixed the null pointer already (will be in the next release).

**Comment by cscp** [comment]
it don't comes now. but sound don't works

**Comment by cscp** [comment]
what can i do against it??

**Comment by itdelatrisu** [comment]
Closing since it's probably not an issue anymore.
