### ISSUE TITLE
Game.update() failure.

### ISSUE THREAD

**Issue by GameDev9** [itdelatrisu/opsu#258]
**Version:** 0.15.0
**Build date:** 2017-02-05 00:04
**OS:** Mac OS X (x86_64)
**JRE:** 1.8.0_111
**OpenGL version:** 2.1 INTEL-10.22.25 (Intel Inc.)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:135)
	at itdelatrisu.opsu.Container.start(Container.java:79)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:216)
Caused by: java.lang.NullPointerException
	at itdelatrisu.opsu.states.Game.calculateStacks(Game.java:2298)
	at itdelatrisu.opsu.states.Game.enter(Game.java:1509)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	... 3 more
```

**Comment by itdelatrisu** [comment]
Thanks for reporting, fixed for next release.  Looks like there was an invalid hit object type in your beatmap (e.g. not a circle/slider/spinner).
