### ISSUE TITLE
Failed to load audio file 'C:\Users\Owner\AppData\Local\osu!\Skins\HappyStick+2\drum-slidertick.wav'.

### ISSUE THREAD

**Issue by MyAimSucks** [itdelatrisu/opsu#259]
**Version:** 0.15.0
**Build date:** 2017-02-05 00:04
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_101
**OpenGL version:** 4.5.0 NVIDIA 378.49 (NVIDIA Corporation)
**Error:** `Failed to load audio file 'C:\Users\Owner\AppData\Local\osu!\Skins\HappyStick+2\drum-slidertick.wav'.`
**Stack trace:**
```
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:98)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:251)
	at itdelatrisu.opsu.states.Splash$1.run(Splash.java:138)
```

**Comment by Lemmmy** [comment]
possibly due to `!` or `+` in paths.

**Comment by itdelatrisu** [comment]
Can you upload the file?

@Lemmmy: external skin, that's not it.

**Comment by Lyonlancer5** [comment]
> Error: Failed to load audio file 'C:\Users\Owner\AppData\Local\osu!\Skins\HappyStick+2\drum-slidertick.wav'

#292 is probably related to this, because the path name contains an `!` (the folder of osu!)

I'm going to test this as soon as possible as I'm also setting up an experiments fork for this project (e.g. LWJGL 3 + Slick2D update + updated libraries)

**Comment by itdelatrisu** [comment]
@Lyonlancer5: That's not the problem - that's an external folder so it's unaffected by the stupid JAR syntax.

If you managed to get Slick working with LWJGL3, congrats to you. o.o

**Comment by k1nzy** [comment]
Are you trying to add a skin to opsu's database? you need to open and close a few times then it should load up your skin if theres's a error with the music just restart a few times again or you can try deleteing that wav file worked for me happy to help if it worked
