### ISSUE TITLE
Failed to load audio file 'applause.wav'.

### ISSUE THREAD

**Issue by LzyAWP-Fred** [itdelatrisu/opsu#267]
**Version:** 0.15.0
**Build date:** 2017-02-05 00:04
**OS:** Linux (amd64)
**JRE:** 1.8.0_121
**OpenGL version:** 3.0 Mesa 13.0.4 (nouveau)
**Error:** `Failed to load audio file 'applause.wav'.`
**Stack trace:**
```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 22050.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1052)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:192)
	at itdelatrisu.opsu.audio.MultiClip.<init>(MultiClip.java:116)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:136)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:99)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:230)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```

**Comment by itdelatrisu** [comment]
Linking #284

**Comment by kolorafa** [comment]
**Version:** 0.16.0
**Build date:** 2017-09-10 08:49
**OS:** Linux (amd64)
**JRE:** 1.8.0_144
**OpenGL version:** 4.5.0 NVIDIA 384.59 (NVIDIA Corporation)
**Error:** `Could not start a clip 'normal-hitwhistle.wav'.`
**Stack trace:**
```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1052)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:213)
	at itdelatrisu.opsu.audio.MultiClip.start(MultiClip.java:135)
	at itdelatrisu.opsu.audio.SoundController.playClip(SoundController.java:308)
	at itdelatrisu.opsu.audio.SoundController.playHitSound(SoundController.java:355)
	at itdelatrisu.opsu.GameData.handleHitResult(GameData.java:1590)
	at itdelatrisu.opsu.GameData.sendHitResult(GameData.java:1648)
	at itdelatrisu.opsu.objects.Circle.mousePressed(Circle.java:159)
	at itdelatrisu.opsu.states.Game.sendGameKeyPress(Game.java:2201)
	at itdelatrisu.opsu.states.Game.runReplayFrame(Game.java:2166)
	at itdelatrisu.opsu.states.Game.addReplayFrameAndRun(Game.java:2153)
	at itdelatrisu.opsu.states.Game.gameKeyPressed(Game.java:1407)
	at itdelatrisu.opsu.states.Game.mousePressed(Game.java:1367)
	at org.newdawn.slick.state.StateBasedGame.mousePressed(StateBasedGame.java:499)
	at org.newdawn.slick.Input.poll(Input.java:1241)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
```
