### ISSUE TITLE
Failed to load audio file 'failsound.wav'.

### ISSUE THREAD

**Issue by Acrylami** [itdelatrisu/opsu#273]
**Version:** 0.15.0
**Build date:** 2017-02-05 00:04
**OS:** Windows 7 (x86)
**JRE:** 1.7.0_51
**OpenGL version:** 3.1.0 - Build 9.17.10.4229 (Intel)
**Error:** `Failed to load audio file 'failsound.wav'.`
**Stack trace:**
```
java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED unknown sample rate, 16 bit, stereo, 4 bytes/frame, big-endian is supported.
	at javax.sound.sampled.AudioSystem.getLine(Unknown Source)
	at javax.sound.sampled.AudioSystem.getClip(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:139)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:99)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:230)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```

**Comment by itdelatrisu** [comment]
Is this with a custom skin or the default files?  If custom, could you upload or link the audio file?

**Comment by Acrylami** [comment]
Default. I only just downloaded it and this was the error upon running it.
