### ISSUE TITLE
Failed to prepare beatmap statements.

### ISSUE THREAD

**Issue by darkralts** [itdelatrisu/opsu#274]
**Version:** 0.14.0
**Build date:** 2017-01-09 07:37
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_121
**Error:** `Failed to prepare beatmap statements.`
**Stack trace:**
```
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table beatmaps has 49 columns but 47 values were supplied)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
	at org.sqlite.core.DB.prepare(DB.java:227)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:150)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:46)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:173)
```

**Comment by itdelatrisu** [comment]
Switch to a newer version (you're running 0.14.0, latest is 0.15.0, but your database is from 0.15.0).

**Comment by darkralts** [comment]
ok but now this happens 
![image](https://cloud.githubusercontent.com/assets/16366107/24430155/436d6d8e-13e3-11e7-9ff7-4ae4f58c144e.png)
