### ISSUE TITLE
opsu. failed to set image. osu wont open.

### ISSUE THREAD

**Issue by darkralts** [itdelatrisu/opsu#275]
![image](https://cloud.githubusercontent.com/assets/16366107/24388040/4c4a3b78-1346-11e7-9048-e8658c54b008.png)
 for some reason this happens every time i start opsu. any help is needed please

**Comment by darkralts** [comment]
and after i press close the game crashes

**Comment by itdelatrisu** [comment]
Sorry, not sure why this would happen if you don't provide more details.  Is there anything in your `.opsu.log` file?  How are you launching the game (file location, and are you just double-clicking on the JAR?).

**Comment by darkralts** [comment]
i just downloaded it, double clicked jar.

**Comment by cutiquay25** [comment]
I have this problem too, just downloaded and start it up with Java
When I open it up, these error messages pop up.
![image](https://cloud.githubusercontent.com/assets/28441311/25745052/59d7c270-31c7-11e7-82c7-340fcf0641a4.png)
![image](https://cloud.githubusercontent.com/assets/28441311/25745067/678e97e0-31c7-11e7-804f-f7023a4b50f1.png)
![image](https://cloud.githubusercontent.com/assets/28441311/25745074/7288ab68-31c7-11e7-8219-c70f914a3633.png)
![image](https://cloud.githubusercontent.com/assets/28441311/25745086/7d93a472-31c7-11e7-8870-0017e71a9fd5.png)
And then the opsu disappear
What should I do to fix this?

**Comment by itdelatrisu** [comment]
Please attach your logs... Look for the file `.opsu.log` in the same folder and paste the contents here or upload the file.

Try running the jar from your Desktop.  If that doesn't work, open a Terminal/Command Prompt, navigate to the folder, and run it with `java -jar opsu-0.13.0.jar`.

**Comment by cutiquay25** [comment]
Here's my logs
"Sat May 06 15:30:19 ICT 2017 ERROR:Pixel format not accelerated
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.newdawn.slick.AppGameContainer.tryCreateDisplay(AppGameContainer.java:302)
	at org.newdawn.slick.AppGameContainer.access$000(AppGameContainer.java:34)
	at org.newdawn.slick.AppGameContainer$2.run(AppGameContainer.java:367)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:348)
	at itdelatrisu.opsu.Container.runSetup(Container.java:111)
	at itdelatrisu.opsu.Container.start(Container.java:76)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:216)
Sat May 06 15:30:21 ICT 2017 ERROR:Attempt to allocate a texture to big for the current hardware
java.io.IOException: Attempt to allocate a texture to big for the current hardware
	at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:320)
	at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:254)
	at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:187)
	at org.newdawn.slick.Image.<init>(Image.java:222)
	at org.newdawn.slick.Image.<init>(Image.java:196)
	at org.newdawn.slick.Image.<init>(Image.java:184)
	at org.newdawn.slick.Image.<init>(Image.java:162)
	at itdelatrisu.opsu.GameImage.loadImageSingle(GameImage.java:780)
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:694)
	at itdelatrisu.opsu.Utils.init(Utils.java:152)
	at itdelatrisu.opsu.states.Splash.init(Splash.java:105)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:171)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
	at itdelatrisu.opsu.Container.runSetup(Container.java:117)
	at itdelatrisu.opsu.Container.start(Container.java:76)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:216)
Sat May 06 15:30:21 ICT 2017 ERROR:Failed to set image 'menu-background'.
Sat May 06 15:30:22 ICT 2017 ERROR:Could not find default image 'menu-background'.
Sat May 06 15:30:23 ICT 2017 ERROR:Attempt to allocate a texture to big for the current hardware
java.io.IOException: Attempt to allocate a texture to big for the current hardware
	at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:320)
	at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:254)
	at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:187)
	at org.newdawn.slick.Image.<init>(Image.java:222)
	at org.newdawn.slick.Image.<init>(Image.java:196)
	at org.newdawn.slick.Image.<init>(Image.java:184)
	at org.newdawn.slick.Image.<init>(Image.java:162)
	at itdelatrisu.opsu.GameImage.loadImageSingle(GameImage.java:780)
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:694)
	at itdelatrisu.opsu.Utils.init(Utils.java:152)
	at itdelatrisu.opsu.states.Splash.init(Splash.java:105)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:171)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
	at itdelatrisu.opsu.Container.runSetup(Container.java:117)
	at itdelatrisu.opsu.Container.start(Container.java:76)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:216)
Sat May 06 15:30:23 ICT 2017 ERROR:Failed to set image 'search-background'.
Sat May 06 15:30:23 ICT 2017 ERROR:Could not find default image 'search-background'.
Sat May 06 15:30:24 ICT 2017 ERROR:Your OpenGL card does not support offscreen buffers and hence can't handle the dynamic images required for this application.
org.newdawn.slick.SlickException: Your OpenGL card does not support offscreen buffers and hence can't handle the dynamic images required for this application.
	at org.newdawn.slick.opengl.pbuffer.GraphicsFactory.init(GraphicsFactory.java:46)
	at org.newdawn.slick.opengl.pbuffer.GraphicsFactory.createGraphics(GraphicsFactory.java:120)
	at org.newdawn.slick.opengl.pbuffer.GraphicsFactory.getGraphicsForImage(GraphicsFactory.java:91)
	at org.newdawn.slick.Image.getGraphics(Image.java:474)
	at itdelatrisu.opsu.states.Game.init(Game.java:350)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:171)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
	at itdelatrisu.opsu.Container.runSetup(Container.java:117)
	at itdelatrisu.opsu.Container.start(Container.java:76)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:216)"

**Comment by itdelatrisu** [comment]
Okay, that looks like a problem with your graphics card.  How old is it?  Try updating your graphics drivers and see if this works.

**Comment by NotDevLper** [comment]
i have same error

**Comment by NotDevLper** [comment]
does opsu! need opengl 3.0?

**Comment by TheRealAhri** [comment]
Hi! I have the same problem, I have a 7 year old graphics card "Intel HD 5000" and it runs pretty much anything with bunch of tweaks, including MC or osu! stable. This is the only thing I cannot run no matter what I do, I tried changing the picture, the game files but nothing worked. If you could please find a solution or make a version for worse pc's like we all have here it would be great. And before you ask me to update my graphics drivers: "We are not publishing any new graphics drivers for your type since 2017"  -Intel. So no, not gonna do that.
