### ISSUE TITLE
Could not connect to database: 'C:\Users\frosc\Desktop\opsu!\itdelatrisu-opsu-05eda48\.opsu.db'.

### ISSUE THREAD

**Issue by frosch1q** [itdelatrisu/opsu#292]
**Version:** ${version}
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_131
**Error:** `Could not connect to database: 'C:\Users\frosc\Desktop\opsu!\itdelatrisu-opsu-05eda48\.opsu.db'.`
**Stack trace:**
```
java.sql.SQLException: Error opening connection
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:215)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:133)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:46)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:176)
Caused by: java.lang.NullPointerException
	at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:203)
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:334)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64)
	at org.sqlite.core.NativeDB.load(NativeDB.java:56)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:211)
	... 12 more
```

**Comment by itdelatrisu** [comment]
How are you running this?  Are you following the build instructions in the README?  (Asking because your "version" field wasn't filled.)

**Comment by Lyonlancer5** [comment]
This seems to happen with directory names containing non-alphanumeric characters, especially the `!` character. Maybe it has something to do with how the SQL library handles file names?

Test cases:
- Case 1, with `!`
> Version: 0.15.0
> OS used: Windows 10 (x86) VM, Windows 8.1 (x64), Windows 7 (x86 and x64) VM
> JRE: 1.8.0_131
>Directory name: 'C:\Users\theunnamed\Desktop\opsu!\
> Startup script: 'java -jar opsu-0.15.0.jar -XX:+UseG1GC'
>
>Result: [Almost same stacktrace above](https://pastebin.com/G6KmwqfJ)

- Case 2, without  `!`
> Version: 0.15.0
> OS used: Windows 10 (x86) VM, Windows 8.1 (x64), Windows 7 (x86 and x64) VM
> JRE: 1.8.0_131
>Directory name: 'C:\Users\theunnamed\Desktop\opsu\
> Startup script: 'java -jar opsu-0.15.0.jar -XX:+UseG1GC'
>
> Result: Executes and closes normally

Other test case pictures, same `!` folder name:
![trace3](https://cloud.githubusercontent.com/assets/7628669/26024674/e210f868-3808-11e7-86dc-369b7e4a838d.png)
![trace4](https://cloud.githubusercontent.com/assets/7628669/26024675/e6e29176-3808-11e7-8763-8cb46b705198.png)
![trace5](https://cloud.githubusercontent.com/assets/7628669/26024676/e9aff6b4-3808-11e7-8dd9-71b97bc930d2.png)

**Comment by yugecin** [comment]
`!` is a special token used to note a resource is inside a jarfile, so there's no known way around this except for using a directory without `!` (see also http://bugs.java.com/view_bug.do?bug_id=4523159).
But normally Opsu! informs you about that (see https://github.com/itdelatrisu/opsu/blob/9074d43a7ec7f9603e977991e60e2ac0d1a5b3e8/src/itdelatrisu/opsu/Opsu.java#L284), but it looks like the exception is caught in `DBController.java` which doesn't check if it's being run in a directory containing `!` (see https://github.com/itdelatrisu/opsu/blob/9074d43a7ec7f9603e977991e60e2ac0d1a5b3e8/src/itdelatrisu/opsu/db/DBController.java#L68), this should be fixed

**Comment by itdelatrisu** [comment]
Okay, thanks both of you for the details.  Like yugecin said, you can't have a `!` in your path, but the game's supposed to tell you that.  Blame 9074d43, I didn't test this carefully enough. :/  Fix coming soon.
