### ISSUE TITLE
[Aspire 2017] 

### ISSUE THREAD

**Issue by Leidi-Kana** [itdelatrisu/opsu#297]

**Comment by Leidi-Kana** [comment]
These are the bizarre happenings when trying to render it (as of `0.15.0`)

![screenshot_20170528_223836](https://cloud.githubusercontent.com/assets/17941162/26529691/6ef86316-43f7-11e7-8472-3b9ca307b80d.png)
![screenshot_20170528_223924](https://cloud.githubusercontent.com/assets/17941162/26529692/6efb6d72-43f7-11e7-9734-58f9ea5848f6.png)
![screenshot_20170528_223928](https://cloud.githubusercontent.com/assets/17941162/26529693/6f049302-43f7-11e7-88f4-6a778f275f7e.png)

After that, this crash happened:
<pre>
Sun May 28 22:39:30 CST 2017 ERROR:Game.render() failure.
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:738)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:135)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at itdelatrisu.opsu.render.CurveRenderState.renderCurve(CurveRenderState.java:456)
	at itdelatrisu.opsu.render.CurveRenderState.draw(CurveRenderState.java:125)
	at itdelatrisu.opsu.objects.curves.Curve.draw(Curve.java:156)
	at itdelatrisu.opsu.objects.Slider.draw(Slider.java:221)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1732)
	at itdelatrisu.opsu.states.Game.render(Game.java:686)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:732)
	... 3 more
</pre>

**Comment by tpenguinltg** [comment]
What an interesting map.

Here's the crash log when I tried to run it (commit aa9ee92, the current HEAD):
```
Sun May 28 15:07:20 EDT 2017 ERROR:Game.render() failure.
org.newdawn.slick.SlickException: Game.render() failure.
        at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
        at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
        at itdelatrisu.opsu.Container.start(Container.java:80)
        at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at itdelatrisu.opsu.render.CurveRenderState.renderCurve(CurveRenderState.java:456)
        at itdelatrisu.opsu.render.CurveRenderState.draw(CurveRenderState.java:125)
        at itdelatrisu.opsu.objects.curves.Curve.draw(Curve.java:156)
        at itdelatrisu.opsu.objects.Slider.draw(Slider.java:221)
        at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1698)
        at itdelatrisu.opsu.states.Game.render(Game.java:661)
        at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
        at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
        ... 3 more
```

There seems to be a considerable slow-down during the parts that are shown above, probably due to the sheer number of objects (something similar happens in the [Windows XP Media Edition](https://osu.ppy.sh/b/644025&m=0) map, except it isn't enough to crash). It seems to just run really slowly using experimental sliders and not crash.
