### ISSUE TITLE
[Aspire 2017] "Crashpire"

### ISSUE THREAD

**Issue by Leidi-Kana** [itdelatrisu/opsu#302]
I found another Aspire map, _it didn't end well..._

This map: [Helblinde - The Solace of Oblivion (mapped by MinG3012)](https://osu.ppy.sh/s/594828)
<details>
<summary>Broken stuff</summary>
<ul>
<li>-1 star rating</li>
<li>Negative infinity BPM</li>
<li>~1.5k combo on some sliders for about a second</li>
</ul></details><br>

Upon **clicking it on song select**, the following exception is thrown:

<pre>
Sun Jun 4 01:24:49 CST 2017 ERROR:null
java.lang.NegativeArraySizeException
	at itdelatrisu.opsu.objects.curves.EqualDistanceMultiCurve.init(EqualDistanceMultiCurve.java:65)
	at itdelatrisu.opsu.objects.curves.LinearBezier.<init>(LinearBezier.java:83)
	at itdelatrisu.opsu.beatmap.HitObject.getSliderCurve(HitObject.java:430)
	at itdelatrisu.opsu.beatmap.tpSlider.<init>(BeatmapDifficultyCalculator.java:526)
	at itdelatrisu.opsu.beatmap.tpHitObject.<init>(BeatmapDifficultyCalculator.java:336)
	at itdelatrisu.opsu.beatmap.BeatmapDifficultyCalculator.calculate(BeatmapDifficultyCalculator.java:146)
	at itdelatrisu.opsu.states.SongMenu.calculateStarRatings(SongMenu.java:1972)
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1751)
	at itdelatrisu.opsu.states.SongMenu.moveFocus(SongMenu.java:1643)
	at itdelatrisu.opsu.states.SongMenu.keyPressed(SongMenu.java:1275)
	at org.newdawn.slick.state.StateBasedGame.keyPressed(StateBasedGame.java:445)
	at org.newdawn.slick.Input.poll(Input.java:1197)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
</pre>

<details>
<summary>On a low-spec PC, even vanilla osu! goes poof</summary>
<img src="https://i.ppy.sh/1ca42c14204ae9b13e52737f71e7b2bf76c0d576/687474703a2f2f692e696d6775722e636f6d2f6f3351436578302e706e67" alt="T H A N K S M I N G"></img></details>

**Comment by tpenguinltg** [comment]
On current HEAD, commit 987b21e:
```
Tue Jun 06 23:36:36 EDT 2017 ERROR:null
java.lang.NegativeArraySizeException
	at itdelatrisu.opsu.objects.curves.EqualDistanceMultiCurve.init(EqualDistanceMultiCurve.java:65)
	at itdelatrisu.opsu.objects.curves.LinearBezier.<init>(LinearBezier.java:83)
	at itdelatrisu.opsu.beatmap.HitObject.getSliderCurve(HitObject.java:430)
	at itdelatrisu.opsu.beatmap.tpSlider.<init>(BeatmapDifficultyCalculator.java:526)
	at itdelatrisu.opsu.beatmap.tpHitObject.<init>(BeatmapDifficultyCalculator.java:336)
	at itdelatrisu.opsu.beatmap.BeatmapDifficultyCalculator.calculate(BeatmapDifficultyCalculator.java:146)
	at itdelatrisu.opsu.states.SongMenu.calculateStarRatings(SongMenu.java:1971)
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1750)
	at itdelatrisu.opsu.states.SongMenu.moveFocus(SongMenu.java:1642)
	at itdelatrisu.opsu.states.SongMenu.keyPressed(SongMenu.java:1274)
	at org.newdawn.slick.state.StateBasedGame.keyPressed(StateBasedGame.java:445)
	at org.newdawn.slick.Input.poll(Input.java:1197)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
```

**Comment by tpenguinltg** [comment]
Just to keep things in one place, it appears this map has sliders with negative `pixelLength`, with at least two of them evaluating to `-Infinity` (lines 1043 and 1047 of the beatmap file have a `pixelLength` of `-1.79769313486231E+308`). Additionally, it seems the third(?) `LinearBezier` loaded passes down an empty `beziers` list.

**Comment by sr229** [comment]
Lazer seems to cope out with this negative values, you might wanna check out their Beatmap handling code for reference
