### ISSUE TITLE
WHEN DELETING ALL BEATMAP ON-GAME

### ISSUE THREAD

**Issue by flaze216** [itdelatrisu/opsu#305]
When I delete all of the beatmap that I have in-game (not using the folder, using the client itself), the game crashes. Please make it so that it redirects to the main menu when you deleted all of your beatmap instead of crashing.

**Comment by itdelatrisu** [comment]
Can you post the error?  You can paste the contents of `.opsu.log` here.

**Comment by flaze216** [comment]
Run Date: Wed Jun 28 08:42:56 GMT+08:00 2017
Warn: Cannot find theme song [/storage/emulated/0/theme.mp3]. 
Error: ** Uncaught Exception! ** 
java.lang.NullPointerException: Attempt to read from field 'int itdelatrisu.opsu.beatmap.Beatmap.previewTime' on a null object reference
	at itdelatrisu.opsu.audio.MusicController.loopTrackIfEnded(MusicController.java:466)
	at itdelatrisu.opsu.states.SongMenu.update(SongMenu.java:842)
	at fluddokt.opsu.fake.StateBasedGame.render(StateBasedGame.java:122)
	at fluddokt.opsu.fake.GameOpsu.pause(GameOpsu.java:51)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:432)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by flaze216** [comment]
Remove this if it's an android version problem

**Comment by itdelatrisu** [comment]
Seems to work fine on the desktop version, so closing this issue.
