### ISSUE TITLE
Failed to load audio file 'failsound.wav'.

### ISSUE THREAD

**Issue by lulufixcs** [itdelatrisu/opsu#308]
**Version:** 0.15.0
**Build date:** 2017-02-05 00:04
**OS:** Mac OS X (x86_64)
**JRE:** 1.8.0_131
**OpenGL version:** 2.1 INTEL-10.0.37 (Intel Inc.)
**Error:** `Failed to load audio file 'failsound.wav'.`
**Stack trace:**
```
java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED unknown sample rate, 16 bit, stereo, 4 bytes/frame, big-endian is supported.
	at javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:479)
	at javax.sound.sampled.AudioSystem.getClip(AudioSystem.java:522)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:139)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:99)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:230)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```

**Comment by tpenguinltg** [comment]
Are you using a custom skin? If so, what is it?
