### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by cgarcia2097** [itdelatrisu/opsu#309]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Linux (arm)
**JRE:** 1.8.0_65
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.UnsatisfiedLinkError: /home/pi/Downloads/Natives/liblwjgl.so: /home/pi/Downloads/Natives/liblwjgl.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
```

**Comment by tpenguinltg** [comment]
This might be exactly what it says in the error message, that the library isn't built for ARM.

Can you please post the output of these two commands?
```sh
file /home/pi/Downloads/Natives/liblwjgl.so
```
```sh
uname -a
```

**Comment by yugecin** [comment]
lwjgl doesn't provide binaries for ARM, I think you'll have to compile them yourself

**Comment by cgarcia2097** [comment]
` file /home/pi/Downloads/Natives/liblwjgl.so `

Output:
`/home/pi/Downloads/Natives/liblwjgl.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=9ef3fe71bdc1625ae5e589f417b770c1e50a2a6f, stripped`

`uname -a`

Output:
`Linux animepi 4.9.36-v7+ #1015 SMP Thu Jul 6 16:14:20 BST 2017 armv7l GNU/Linux`

**Comment by tpenguinltg** [comment]
Figured it was a RPi. Yeah, the problem is that RPi is ARM and it can't run a library built for x86.

You shouldn't need to cross-compile anything (cross-compiling would be compiling Windows binaries on Linux, for example). You should be able to follow the build instructions for Linux for lwjgl, but make sure you grab [version 2](http://legacy.lwjgl.org/).

**Comment by Lyonlancer5** [comment]
Based off from [`How to setup Minecraft 1.12.1 on Raspberry Pi 3`](https://www.raspberrypi.org/forums/viewtopic.php?t=186547)

You can locally repack your opsu! copy with an ARM build of LWJGL 2 instead, although this build uses `2.9.4-nightly-20150209` rather than the `2.9.3` that opsu! originally uses.
However, in testing, the Pi can't really handle opsu! due to hardware limitations.

1. Follow steps 1-5 of [`How to setup Minecraft 1.12.1 on Raspberry Pi 3`](https://www.raspberrypi.org/forums/viewtopic.php?t=186547)
2. Download the LWJGL ARM build from here (links also from the same forum post):
> [LWJGL JAR file](https://www.dropbox.com/s/mj15sz3bub4dmr6/lwjgl-2.9.4-nightly-20150209.jar)
> [liblwjgl.so](https://www.dropbox.com/s/4oxcvz3ky7a3x6f/liblwjgl.so)
> [libopenal.so](https://www.dropbox.com/s/m0r8e01jg2og36z/libopenal.so)

3. Unpack the opsu! jar into an empty folder
4. Unpack the LWJGL jar into a separate empty folder
5. Copy the `org` folder of the LWJGL folder to the folder of the extracted opsu! jar.
6. Overwrite the `liblwjgl.so` and `libopenal.so` files of the opsu! folder with the downloaded  `liblwjgl.so` and `libopenal.so`.
7. Repack the contents of the opsu! folder into a ZIP file and rename the `.zip` extension with a `.jar` extension.
8. Run as usual, via `java -jar <your-jar-name>.jar` or by double-clicking.
