### ISSUE TITLE
Failed to load audio file 'C:\Users\creep\AppData\Local\osu!\Skins\Asteriskk v2 Blue\normal-slidertick.wav'.

### ISSUE THREAD

**Issue by CreamYT** [itdelatrisu/opsu#311]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_121
**OpenGL version:** 4.3.0 - Build 10.18.15.4248 (Intel)
**Error:** `Failed to load audio file 'C:\Users\creep\AppData\Local\osu!\Skins\Asteriskk v2 Blue\normal-slidertick.wav'.`
**Stack trace:**
```
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:98)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:251)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```

**Comment by k1nzy** [comment]
Are you trying to add a skin to opsu's database? you need to open and close a few times then it should load up your skin if theres's a error with the music just restart a few times again or you can try deleteing that wav file

**Comment by CreamYT** [comment]
I literally dont remember sending you that! XD
