### ISSUE TITLE
Failed to initialise the LWJGL display

### ISSUE THREAD

**Issue by LovelyA72** [itdelatrisu/opsu#316]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_144
**Stack trace:**
```
org.newdawn.slick.SlickException: Failed to initialise the LWJGL display
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:378)
	at itdelatrisu.opsu.Container.runSetup(Container.java:118)
	at itdelatrisu.opsu.Container.start(Container.java:77)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
```

**Comment by tpenguinltg** [comment]
Linking #248 and #250
