### ISSUE TITLE
map loading error

### ISSUE THREAD

**Issue by LovelyA72** [itdelatrisu/opsu#317]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Mac OS X (x86_64)
**JRE:** 1.8.0_141
**OpenGL version:** 2.1 ATI-1.42.6 (ATI Technologies Inc.)
**Stack trace:**
```
java.lang.NegativeArraySizeException
	at itdelatrisu.opsu.objects.curves.EqualDistanceMultiCurve.init(EqualDistanceMultiCurve.java:65)
	at itdelatrisu.opsu.objects.curves.LinearBezier.<init>(LinearBezier.java:83)
	at itdelatrisu.opsu.beatmap.HitObject.getSliderCurve(HitObject.java:430)
	at itdelatrisu.opsu.beatmap.tpSlider.<init>(BeatmapDifficultyCalculator.java:526)
	at itdelatrisu.opsu.beatmap.tpHitObject.<init>(BeatmapDifficultyCalculator.java:336)
	at itdelatrisu.opsu.beatmap.BeatmapDifficultyCalculator.calculate(BeatmapDifficultyCalculator.java:146)
	at itdelatrisu.opsu.states.SongMenu.calculateStarRatings(SongMenu.java:1971)
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1750)
	at itdelatrisu.opsu.states.SongMenu.moveFocus(SongMenu.java:1642)
	at itdelatrisu.opsu.states.SongMenu.keyPressed(SongMenu.java:1286)
	at org.newdawn.slick.state.StateBasedGame.keyPressed(StateBasedGame.java:445)
	at org.newdawn.slick.Input.poll(Input.java:1197)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
```

**Comment by tpenguinltg** [comment]
Which map is this?

(It looks like some `HitObject`'s `pixelLength` might be negative.)

**Comment by LovelyA72** [comment]
I am not sure... When i scroll to that map it crash immediately. I even dont have time to see which map it is

**Comment by tpenguinltg** [comment]
I think I've figured it out. It's "The Solace of Oblivion" ([594828](https://osu.ppy.sh/s/594828) from Aspire 2017, isn't it?

Linking #302.

**Comment by LovelyA72** [comment]
<img width="553" alt="qq20170920-105454 2x" src="https://user-images.githubusercontent.com/29054052/30624835-29eb38de-9df2-11e7-88ba-6fd5084fbd4e.png">
I think you're correct :)
