### ISSUE TITLE
All the videos is unable to play

### ISSUE THREAD

**Issue by LovelyA72** [itdelatrisu/opsu#318]
When i tried to play some maps with video, it will popup a message and said error on loading video. And all these maps's video in osu!(ppy edition) is working fine.

**Comment by LovelyA72** [comment]
Thu Sep 14 20:33:41 HKT 2017 ERROR:Cannot run program "/Users/LuoTianyi/Desktop/opsu/Natives/ffmpeg-mac": error=13, Permission denied
java.io.IOException: Cannot run program "/Users/LuoTianyi/Desktop/opsu/Natives/ffmpeg-mac": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at itdelatrisu.opsu.video.FFmpeg.extractMetadata(FFmpeg.java:97)
	at itdelatrisu.opsu.video.Video.<init>(Video.java:80)
	at itdelatrisu.opsu.states.Game.loadVideo(Game.java:1976)
	at itdelatrisu.opsu.states.Game.enter(Game.java:1654)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 9 more

**Comment by LovelyA72** [comment]
well... it looks like i have to copy a ffmpeg from jar file... After i did that it works awesome
