### ISSUE TITLE
Failed to load audio file 'E:\osu!\Skins\Remyria's Skin Yugen\spinnerbonus.wav'.

### ISSUE THREAD

**Issue by Remyria** [itdelatrisu/opsu#320]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Windows 7 (amd64)
**JRE:** 1.8.0_131
**OpenGL version:** 4.5.0 NVIDIA 368.22 (NVIDIA Corporation)
**Error:** `Failed to load audio file 'E:\osu!\Skins\Remyria's Skin Yugen\spinnerbonus.wav'.`
**Stack trace:**
```
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:98)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:230)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```

**Comment by LovelyA72** [comment]
i remember java cannot read file from a directory that contains ''!'' or sth else than letters or number

**Comment by tpenguinltg** [comment]
@LovelyA72 As I recall, that only applied to running the opsu! jar in a path that contains `!`. External files are fine.

**Comment by k1nzy** [comment]
Are you trying to add a skin to opsu's database? you need to open and close a few times then it should load up your skin if theres's a error with the music just restart a few times again or you can try deleteing that wav file worked for me happy to help if it worked
