### ISSUE TITLE
Could not play track

### ISSUE THREAD

**Issue by Lucki** [itdelatrisu/opsu#33]
I've a problem with this Beatmap, all others seems fine so far, or I haven't found one with similar error.
When clicking on it, a error-window pops in front containing this:
~~~
Could not play track 'Nightcore - Where Is The Love.mp3'.
java.lang.RuntimeException: Resource not found: /home/lucki/.local/share/opsu/Songs/19882 Baracuda - Where Is The Love (Nightcore Mix)/Nightcore - Where Is The Love.mp3
	at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69)
	at org.newdawn.slick.openal.OpenALStreamPlayer.initStreams(OpenALStreamPlayer.java:149)
	at org.newdawn.slick.openal.OpenALStreamPlayer.play(OpenALStreamPlayer.java:196)
	at org.newdawn.slick.openal.StreamSound.playAsMusic(StreamSound.java:46)
	at org.newdawn.slick.Music.startMusic(Music.java:314)
	at org.newdawn.slick.Music.loop(Music.java:291)
	at org.newdawn.slick.Music.loop(Music.java:264)
	at itdelatrisu.opsu.audio.MusicController.playAt(MusicController.java:136)
	at itdelatrisu.opsu.audio.MusicController.loadTrack(MusicController.java:119)
	at itdelatrisu.opsu.audio.MusicController.access$000(MusicController.java:42)
	at itdelatrisu.opsu.audio.MusicController$1.run(MusicController.java:86)
Sat Mar 07 13:37:32 CET 2015 WARN:OpenALStreamPlayer: setPosition: failed to skip.
~~~

Edit: Holding F2 gives me a second and third Song with error:
~~~
Could not play track 'Electric Six - Gay Bar.mp3'.
java.lang.RuntimeException: Resource not found: /home/lucki/.local/share/opsu/Songs/9550 Electric Six - Gay Bar/Electric Six - Gay Bar.mp3
	at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69)
	at org.newdawn.slick.openal.OpenALStreamPlayer.initStreams(OpenALStreamPlayer.java:149)
	at org.newdawn.slick.openal.OpenALStreamPlayer.play(OpenALStreamPlayer.java:196)
	at org.newdawn.slick.openal.StreamSound.playAsMusic(StreamSound.java:46)
	at org.newdawn.slick.Music.startMusic(Music.java:314)
	at org.newdawn.slick.Music.loop(Music.java:291)
	at org.newdawn.slick.Music.loop(Music.java:264)
	at itdelatrisu.opsu.audio.MusicController.playAt(MusicController.java:136)
	at itdelatrisu.opsu.audio.MusicController.loadTrack(MusicController.java:119)
	at itdelatrisu.opsu.audio.MusicController.access$000(MusicController.java:42)
	at itdelatrisu.opsu.audio.MusicController$1.run(MusicController.java:86)

Sat Mar 07 13:39:23 CET 2015 ERROR:Input does not appear to be an Ogg bitstream.
Sat Mar 07 13:39:23 CET 2015 ERROR:Could not play track 'track10.ogg'.
Sat Mar 07 13:39:23 CET 2015 ERROR:null
Could not play track 'track10.ogg'.
java.lang.NullPointerException
	at java.lang.System.arraycopy(Native Method)
	at com.jcraft.jogg.SyncState.buffer(SyncState.java:66)
	at org.newdawn.slick.openal.OggInputStream.getPageAndPacket(OggInputStream.java:145)
	at org.newdawn.slick.openal.OggInputStream.readPCM(OggInputStream.java:294)
	at org.newdawn.slick.openal.OggInputStream.read(OggInputStream.java:446)
	at org.newdawn.slick.openal.OggInputStream.read(OggInputStream.java:475)
	at org.newdawn.slick.openal.OggInputStream.read(OggInputStream.java:498)
	at org.newdawn.slick.openal.OpenALStreamPlayer.stream(OpenALStreamPlayer.java:276)
	at org.newdawn.slick.openal.OpenALStreamPlayer.startPlayback(OpenALStreamPlayer.java:364)
	at org.newdawn.slick.openal.OpenALStreamPlayer.play(OpenALStreamPlayer.java:202)
	at org.newdawn.slick.openal.StreamSound.playAsMusic(StreamSound.java:46)
	at org.newdawn.slick.Music.startMusic(Music.java:314)
	at org.newdawn.slick.Music.loop(Music.java:291)
	at org.newdawn.slick.Music.loop(Music.java:264)
	at itdelatrisu.opsu.audio.MusicController.playAt(MusicController.java:136)
	at itdelatrisu.opsu.audio.MusicController.loadTrack(MusicController.java:119)
	at itdelatrisu.opsu.audio.MusicController.access$000(MusicController.java:42)
	at itdelatrisu.opsu.audio.MusicController$1.run(MusicController.java:86)
~~~

**Comment by itdelatrisu** [comment]
I mean, "resource not found" means exactly what it sounds like... do the files actually exist?

**Comment by Lucki** [comment]
Yes, they are right there where they should be. Seems like a case sensitive problem, at least for the first two tracks:

Nightcore - Where **Is** The Love.mp3 != Nightcore - Where **is** The Love.mp3:
~~~
lucki@Archlinux ~/.local/share/opsu/Songs % find . -iname 'Nightcore - Where Is The Love.mp3'
./19882 Baracuda - Where Is The Love (Nightcore Mix)/Nightcore - Where is The Love.mp3
~~~
Electric Six - Gay Bar.mp3 != electric six - gay bar.mp3:
~~~
lucki@Archlinux ~/.local/share/opsu/Songs % find . -iname 'Electric Six - Gay Bar.mp3'
./9550 Electric Six - Gay Bar/electric six - gay bar.mp3
~~~
~~~
lucki@Archlinux ~/.local/share/opsu/Songs % find . -iname 'track10.ogg'               
./8768 Type-Moon - Maiden/track10.ogg
~~~

**Comment by Lucki** [comment]
I'm sorry, but the problem still exists. I still get the exact same error message.

**Comment by itdelatrisu** [comment]
Try clearing your cache?

**Comment by Lucki** [comment]
That was the trick ;)
