### ISSUE TITLE
【I have some new(old) crashing map~】Game.update() failure.

### ISSUE THREAD

**Issue by LovelyA72** [itdelatrisu/opsu#333]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_144
**OpenGL version:** 4.5.0 NVIDIA 385.41 (NVIDIA Corporation)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at itdelatrisu.opsu.beatmap.BeatmapHPDropRateCalculator.calculate(BeatmapHPDropRateCalculator.java:91)
	at itdelatrisu.opsu.states.Game.setMapModifiers(Game.java:2035)
	at itdelatrisu.opsu.states.Game.enter(Game.java:1505)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	... 3 more
```
![image](https://user-images.githubusercontent.com/29054052/32168909-4da03262-bda9-11e7-9549-99be5400f3e1.png)
(Ignore that "Cookiezi", this is my modified version)

**Comment by LovelyA72** [comment]
I just find that the length is 0:00...
