### ISSUE TITLE
Could not start a clip 'drum-hitnormal.wav'.

### ISSUE THREAD

**Issue by rodrigorato** [itdelatrisu/opsu#338]
I was playing this map:
https://osu.ppy.sh/s/575767

**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Linux (amd64)
**JRE:** 1.8.0_144
**OpenGL version:** 4.6.0 NVIDIA 387.22 (NVIDIA Corporation)
**Error:** `Could not start a clip 'drum-hitnormal.wav'.`
**Stack trace:**
```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1052)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:213)
	at itdelatrisu.opsu.audio.MultiClip.start(MultiClip.java:135)
	at itdelatrisu.opsu.audio.SoundController.playClip(SoundController.java:308)
	at itdelatrisu.opsu.audio.SoundController.playHitSound(SoundController.java:349)
	at itdelatrisu.opsu.GameData.handleHitResult(GameData.java:1590)
	at itdelatrisu.opsu.GameData.sendHitResult(GameData.java:1648)
	at itdelatrisu.opsu.objects.Circle.mousePressed(Circle.java:159)
	at itdelatrisu.opsu.states.Game.sendGameKeyPress(Game.java:2201)
	at itdelatrisu.opsu.states.Game.runReplayFrame(Game.java:2166)
	at itdelatrisu.opsu.states.Game.addReplayFrameAndRun(Game.java:2153)
	at itdelatrisu.opsu.states.Game.gameKeyPressed(Game.java:1407)
	at itdelatrisu.opsu.states.Game.keyPressed(Game.java:1174)
	at org.newdawn.slick.state.StateBasedGame.keyPressed(StateBasedGame.java:445)
	at org.newdawn.slick.Input.poll(Input.java:1197)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
```

**Comment by tpenguinltg** [comment]
I don't think I can be of any help with solving the issue (there's generally a lot of Linux hitsound issues here), but are you using the default skin or a custom one?

**Comment by rodrigorato** [comment]
That's ok! I was using the default one, it was my first time trying out the game. :)
