### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by wilcooo** [itdelatrisu/opsu#341]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Linux (amd64)
**JRE:** 9-Ubuntu
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static java.lang.String[] java.lang.ClassLoader.sys_paths accessible: module java.base does not "opens java.lang" to unnamed module @48a242ce
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:335)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:278)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:175)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:169)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:168)
```

**Comment by yugecin** [comment]
try running with `java --add-opens java.base/java.lang=ALL-UNNAMED -jar opsu.jar`

**Comment by itdelatrisu** [comment]
Please use Java 7 or 8.
