### ISSUE TITLE
Could not connect to database: '.\.opsu_scores.db'.

### ISSUE THREAD

**Issue by varfobis** [itdelatrisu/opsu#356]
**Version:** 0.12.1
**Build date:** 2016-12-13 14:48
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_161
**Error:** `Could not connect to database: '.\.opsu_scores.db'.`
**Stack trace:**
```
java.sql.SQLException: opening db: '.\.opsu_scores.db': Отказано в доступе
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:203)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
	at itdelatrisu.opsu.db.ScoreDB.init(ScoreDB.java:88)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:47)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:165)
```

**Comment by varfobis** [comment]
Failed to write to file 'C:\WINDOWS\system32\.\.opsu.cfg'.
java.io.FileNotFoundException: .\.opsu.cfg (Отказано в доступе)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at itdelatrisu.opsu.Options.saveOptions(Options.java:1947)
	at itdelatrisu.opsu.Options.parseOptions(Options.java:1903)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:121)

**Comment by varfobis** [comment]
* Uncaught Exception! **
java.lang.UnsatisfiedLinkError: Can't load library: C:\WINDOWS\system32\.\Natives\lwjgl.dll
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:206)

**Comment by itdelatrisu** [comment]
You're running the program wrong (...or you put it in system32).  You're also on a very old version.  Try downloading a new version first from [here](https://github.com/itdelatrisu/opsu/releases), then if running it doesn't work, open a Command Prompt in the directory and type `java -jar opsu-0.16.0.jar`.
