### ISSUE TITLE
Could not start a clip 'drum-hitfinish.wav'.

### ISSUE THREAD

**Issue by Scoopta** [itdelatrisu/opsu#366]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Linux (amd64)
**JRE:** 9.0.1
**OpenGL version:** 3.0 Mesa 17.3.5 (X.Org)
**Error:** `Could not start a clip 'drum-hitfinish.wav'.`
**Stack trace:**
```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:503)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1292)
	at java.desktop/com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:119)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1074)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1041)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:213)
	at itdelatrisu.opsu.audio.MultiClip.start(MultiClip.java:135)
	at itdelatrisu.opsu.audio.SoundController.playClip(SoundController.java:308)
	at itdelatrisu.opsu.audio.SoundController.playHitSound(SoundController.java:357)
	at itdelatrisu.opsu.GameData.sendSliderTickResult(GameData.java:1446)
	at itdelatrisu.opsu.objects.Slider.mousePressed(Slider.java:606)
	at itdelatrisu.opsu.states.Game.sendGameKeyPress(Game.java:2204)
	at itdelatrisu.opsu.states.Game.runReplayFrame(Game.java:2166)
	at itdelatrisu.opsu.states.Game.addReplayFrameAndRun(Game.java:2153)
	at itdelatrisu.opsu.states.Game.gameKeyPressed(Game.java:1407)
	at itdelatrisu.opsu.states.Game.mousePressed(Game.java:1367)
	at org.newdawn.slick.state.StateBasedGame.mousePressed(StateBasedGame.java:499)
	at org.newdawn.slick.Input.poll(Input.java:1241)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
```

**Comment by tpenguinltg** [comment]
Probably a duplicate of #226, #267, #335, #338, and #360.

We don't officially support JRE 9, but that's probably not the issue.
