### ISSUE TITLE
Failed to load audio file 'drum-sliderwhistle.wav'.

### ISSUE THREAD

**Issue by tastysushixd** [itdelatrisu/opsu#369]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Linux (i386)
**JRE:** 1.7.0_80
**OpenGL version:** 2.1 Mesa 8.0.4 (VMware, Inc.)
**Error:** `Failed to load audio file 'drum-sliderwhistle.wav'.`
**Stack trace:**
```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1052)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:213)
	at itdelatrisu.opsu.audio.MultiClip.<init>(MultiClip.java:117)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:136)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:99)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:251)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```

**Comment by tpenguinltg** [comment]
Probably a duplicate of #226, #267, #335, #338, #360 and #366.
