### ISSUE TITLE
The databases could not be initialized.

### ISSUE THREAD

**Issue by MonkeyDLuffy03** [itdelatrisu/opsu#379]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Windows 8.1 (x86)
**JRE:** 1.7.0_79
**Error:** `The databases could not be initialized.`
**Stack trace:**
```
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (duplicate column name: replay)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
	at org.sqlite.core.NativeDB._exec(NativeDB.java:87)
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:116)
	at itdelatrisu.opsu.db.ScoreDB.updateDatabase(ScoreDB.java:210)
	at itdelatrisu.opsu.db.ScoreDB.init(ScoreDB.java:98)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:41)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:124)
```

**Comment by tpenguinltg** [comment]
That's unusual. How long have you had this installation of opsu! for?

**Comment by itdelatrisu** [comment]
Closing, probably not worth figuring out which DB upgrade broke this...
