### ISSUE TITLE
The databases could not be initialized.

### ISSUE THREAD

**Issue by KLOP5** [itdelatrisu/opsu#382]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Linux (amd64)
**JRE:** 1.8.0_162
**Error:** `The databases could not be initialized.`
**Stack trace:**
```
org.sqlite.SQLiteException: [SQLITE_READONLY]  Attempt to write a readonly database (attempt to write a readonly database)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
	at org.sqlite.core.NativeDB._exec(NativeDB.java:87)
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:116)
	at itdelatrisu.opsu.db.BeatmapDB.createDatabase(BeatmapDB.java:200)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:142)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:40)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:124)
```

**Comment by tpenguinltg** [comment]
Some questions:
* How did you install opsu!? Are you directly running the JAR, or did you install it through a distro package (and which one)?
* Is this your first time running opsu!, or have you run it before?
* Are there any other instances of opsu! running?

If you installed the Arch Linux AUR package, the path for the beatmap database is `~/.local/share/opsu/.opsu.db`. Make sure it and the containing directory are owned by your user and have the write permission enabled:

```bash
ls -ld ~/.local/share/opsu/ ~/.local/share/opsu/.opsu.db
```

If you're running the JAR directly, it should be in the same folder as the JAR.

**Comment by KLOP5** [comment]
How did you install opsu!? Are you directly running the JAR, or did you install it through a distro package (and which one)?
- I downloaded the .jar from github and ran this command in a terminal:
sudo java -jar opsu-0.16.0.jar

[Am I using the correct command?]

    Is this your first time running opsu!, or have you run it before?
- First time

    Are there any other instances of opsu! running?
- No

When I tried to run the .jar today I got an interesting new error:

[gabe@localhost Opsu]$ sudo java -jar opsu-0.16.0.jar
No protocol specified

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"

Btw, I found your blog quite interesting.

**Comment by Lemmmy** [comment]
Delete `~/.local/share/opsu/`, and then run the jar again **without `sudo`**.

**Comment by tpenguinltg** [comment]
@KLOP5 As Lemmy suggested, run it without `sudo`. Running things with `sudo` can have unexpected results, and most of the time, you don't need it anyway. In general, don't run things with `sudo` unless you're absolutely sure you need it.

Since you got the JAR from GitHub, the directories it created are in the directory you ran the command in. You'll probably find these files and folders in that directory, and you should delete them with `sudo rm -r` (be careful):
```
.opsu.db
.opsu_scores.db
Import/
Replays/
Screenshots/
Skins/
SongPacks/
Songs/
```

To try running it properly, I suggest creating a new directory (no `sudo`; your user should have read and write access to this new directory) and copying the JAR to that directory. `cd` into that directory and run `java -jar opsu-0.16.0.jar` (again, no `sudo`). This should hopefully work as expected. 

@Lemmmy The JAR from the GitHub release isn't built with `-DXDG=true`, so the various directories are created in the current directory, not in `~/.local/share/opsu/`.
