### ISSUE TITLE
null

### ISSUE THREAD

**Issue by martireg** [itdelatrisu/opsu#383]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Linux (amd64)
**JRE:** 1.8.0_73
**OpenGL version:** 4.5.0 NVIDIA 384.111 (NVIDIA Corporation)
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1765)
	at itdelatrisu.opsu.states.MainMenu.previousTrack(MainMenu.java:1002)
	at itdelatrisu.opsu.states.MainMenu.mousePressed(MainMenu.java:763)
	at org.newdawn.slick.state.StateBasedGame.mousePressed(StateBasedGame.java:499)
	at org.newdawn.slick.Input.poll(Input.java:1241)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
```

**Comment by tpenguinltg** [comment]
Do you remember which beatmap you clicked on?

**Comment by tpenguinltg** [comment]
For anyone wanting to take a look at this, the line numbers have changed a little since this release. The problem here is that `beatmap` is `null` at the `if` statement in line 1767.

https://github.com/itdelatrisu/opsu/blob/e4e571b4170fc39f23c199e25fe6e4146ab814ad/src/itdelatrisu/opsu/states/SongMenu.java#L1765-L1767
