### ISSUE TITLE
Failed to load audio file 'C:\Users\me\Desktop\osu!\Skins\KukiRed\normal-slidertick.wav'.

### ISSUE THREAD

**Issue by CamelCaseMaster** [itdelatrisu/opsu#386]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_161
**OpenGL version:** 4.4.0 - Build 20.19.15.4703 (Intel)
**Error:** `Failed to load audio file 'C:\Users\me\Desktop\osu!\Skins\KukiRed\normal-slidertick.wav'.`
**Stack trace:**
```
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1155)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:98)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:251)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```

**Comment by itdelatrisu** [comment]
Can you upload the file?

**Comment by CamelCaseMaster** [comment]
So late a reply, sorry. Here you go : http://download.osuskins.info/3096/515/KukiRed.osk 14MB skin with the .wav in question
