### ISSUE TITLE
** Uncaught Exception! ** - opsu! on raspberry pi failed

### ISSUE THREAD

**Issue by LovelyA72** [itdelatrisu/opsu#388]
Well... I know playing opsu! on a tiny raspberry pi is definitely not a great idea... But this is the error that it throw to me when I play it on a raspberry pi 3B.
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Linux (arm) - or Raspbian April 2018
**JRE:** 1.8.0_65
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.UnsatisfiedLinkError: /home/pi/opsu/Natives/liblwjgl.so: /home/pi/opsu/Natives/liblwjgl.so: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.lwjgl.Sys$1.run(Sys.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
```

**Comment by tpenguinltg** [comment]
Yeah, we don't ship any binaries built for the ARM architecture. You'd have to build them yourself.

Duplicate of #309
