### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by ctshift** [itdelatrisu/opsu#390]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_131
**OpenGL version:** 4.4.0 - Build 20.19.15.4474 (Intel)
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.OutOfMemoryError: Java heap space
	at org.tukaani.xz.lz.BT4.<init>(Unknown Source)
	at org.tukaani.xz.lz.LZEncoder.getInstance(Unknown Source)
	at org.tukaani.xz.lzma.LZMAEncoderNormal.<init>(Unknown Source)
	at org.tukaani.xz.lzma.LZMAEncoder.getInstance(Unknown Source)
	at org.tukaani.xz.LZMAOutputStream.<init>(Unknown Source)
	at org.tukaani.xz.LZMAOutputStream.<init>(Unknown Source)
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:345)
```

**Comment by Lemmmy** [comment]
[Looks like you ran out of memory.](http://downloadmoreram.com)

**Comment by tpenguinltg** [comment]
Do you remember which beatmap you were playing when this happened? I'm inclined to call this a one-time occurrence unless it happens consistently with whatever beatmap this happened on.

**Comment by ctshift** [comment]
@tpenguinltg It happens whenever I boot opsu, no matter what computer I'm on. It on the other hand, does not happen when I don't have my skin applied.

**Comment by tpenguinltg** [comment]
@ctshift Could you please post the error when it happens on boot? It would give us a better idea of what in the skin is causing the error.

**Comment by tpenguinltg** [comment]
Of course, the quickfix solution is to have you increase the heap size by passing the flag `-Xmx600M` to tell Java to use a maximum heap size of 600MB (or whatever number works if 600 is too small). You can turn that into a Windows shortcut or a batch file to pass it in every time.

But let's continue troubleshooting to make sure there isn't anything in our code that we can optimize.

**Comment by ctshift** [comment]
@tpenguinltg That is the skin, and should I put the error that comes with boot as a new issue or just copy/paste it in here?

**Comment by tpenguinltg** [comment]
@ctshift You can paste it here. The issue at this point is the skin and why it's causing the program to run out of memory, so it's related.
