### ISSUE TITLE
Error while loading empty WAVs

### ISSUE THREAD

**Issue by takase1121** [itdelatrisu/opsu#393]
I saw many WAV loading issues, and I also faced it when using custom skins. But, I found out that it won't load empty (by empty I mean silent) WAVs. Any ideas to fix this, or am I getting the wrong point?

**Comment by tpenguinltg** [comment]
Can you please point us to which files in which skins you're having issues with?

**Comment by takase1121** [comment]
```Sun Jun 03 15:52:14 SGT 2018 ERROR:Failed to load audio file 'C:\osu!\Skins\Nekopara!\readys.wav'.
Sun Jun 03 15:52:14 SGT 2018 ERROR:could not get audio input stream from input URL
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:98)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:230)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
Sun Jun 03 15:52:22 SGT 2018 ERROR:Failed to load audio file 'C:\osu!\Skins\Nekopara!\sectionfail.wav'.
Sun Jun 03 15:52:22 SGT 2018 ERROR:could not get audio input stream from input URL
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:98)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:230)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
Sun Jun 03 15:52:23 SGT 2018 ERROR:Failed to load audio file 'C:\osu!\Skins\Nekopara!\normal-slidertick.wav'.
Sun Jun 03 15:52:23 SGT 2018 ERROR:could not get audio input stream from input URL
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:98)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:251)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
Sun Jun 03 15:52:24 SGT 2018 ERROR:Failed to load audio file 'C:\osu!\Skins\Nekopara!\soft-slidertick.wav'.
Sun Jun 03 15:52:24 SGT 2018 ERROR:could not get audio input stream from input URL
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:98)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:251)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```
[sounds.zip](https://github.com/itdelatrisu/opsu/files/2065768/sounds.zip)

here are the logs and the files.
