### ISSUE TITLE
Failed to load audio file 'normal-hitnormal.wav'.

### ISSUE THREAD

**Issue by sbrl** [itdelatrisu/opsu#407]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Linux (amd64)
**JRE:** 10.0.1
**OpenGL version:** 3.0 Mesa 18.0.0-rc5 (Intel Open Source Technology Center)
**Error:** `Failed to load audio file 'normal-hitnormal.wav'.`
**Stack trace:**
```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:503)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1292)
	at java.desktop/com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:119)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1074)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1041)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:213)
	at itdelatrisu.opsu.audio.MultiClip.<init>(MultiClip.java:117)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:140)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:100)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:255)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```

Just got this after updating to the latest version. Not sure what up.

**Comment by tpenguinltg** [comment]
It's a [known bug](https://github.com/itdelatrisu/opsu/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aaudio+label%3Alinux). Note that we don't officially support JRE 10, but I don't think that's the issue.

**Comment by sbrl** [comment]
@tpenguinltg Ah, I see. I'd certainly be willing to aid in the tracking down of this bug, if given some instructions of things to try. Looks like this is a duplicate of #369. Would you like me to close this and comment there instead?

**Comment by tpenguinltg** [comment]
@sbrl If you're confident that it's a duplicate, then yes, feel free to do so. (@itdelatrisu: if this is closed before you get to it, you should consider tagging it anyway).

You'll probably find #226 to be the most useful thread.

**Comment by sbrl** [comment]
Hrm. I don't think that this is a duplicate of #226. #369 seems more similar though. I say this because this error ocurrs on startup. I can't even click or do anything, unlike the report in #226.

**Comment by tpenguinltg** [comment]
#369 has the same stack trace, yes, but I'm convinced that they both have the same root cause and can be fixed with the same patch. See this comment: https://github.com/itdelatrisu/opsu/issues/226#issuecomment-279191957

**Comment by sbrl** [comment]
@tpenguinltg Hrm, I see. Is there anything I can do to help at all?

**Comment by tpenguinltg** [comment]
If you have the time and ability to do so, the best thing you can do is to play around with some of the proposed solutions near the end of #226. I don't think any of us have the time to invest into this (I certainly don't), so it would be a great help.

If not, then I guess you're stuck sitting and waiting unless you can think of anything else.

**Comment by tpenguinltg** [comment]
Although one thing you can try is to see if you get the error when you have no other applications playing audio (or as few as possible). Also, I don't think this matters, but is this the default skin or do you have a custom one?

**Comment by sbrl** [comment]
I didn't even know you could customise the skin of opsu!

I might look into that.

Yep - if I start it as soon as I start my laptop, it works fine.
