### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by xasuma** [itdelatrisu/opsu#41]
**Version:** 0.7.0
**Build date:** 2015-03-08 21:49
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.db.OsuDB.setStatementFields(OsuDB.java:309)
	at itdelatrisu.opsu.db.OsuDB.insert(OsuDB.java:250)
	at itdelatrisu.opsu.OsuParser.parseDirectories(OsuParser.java:184)
	at itdelatrisu.opsu.OsuParser.parseAllFiles(OsuParser.java:78)
	at itdelatrisu.opsu.states.Splash$1.run(Splash.java:106)
```

**Comment by itdelatrisu** [comment]
I probably fixed it -- try re-downloading the [release](https://github.com/itdelatrisu/opsu/releases/download/0.7.0/opsu-0.7.0.jar).  You might have to delete the `.opsu.db` cache.
