### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by memebae** [itdelatrisu/opsu#411]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_171
**OpenGL version:** 4.5.13474 Compatibility Profile Context 22.19.162.4 (ATI Technologies Inc.)
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.String.<init>(String.java:166)
	at java.io.WinNTFileSystem.resolve(WinNTFileSystem.java:267)
	at java.io.File.<init>(File.java:367)
	at itdelatrisu.opsu.db.BeatmapDB.setBeatmapFields(BeatmapDB.java:567)
	at itdelatrisu.opsu.db.BeatmapDB.load(BeatmapDB.java:519)
	at itdelatrisu.opsu.beatmap.BeatmapParser.parseDirectories(BeatmapParser.java:231)
	at itdelatrisu.opsu.beatmap.BeatmapParser.parseAllFiles(BeatmapParser.java:100)
	at itdelatrisu.opsu.states.SongMenu$BeatmapReloadThread.reloadBeatmaps(SongMenu.java:260)
	at itdelatrisu.opsu.states.SongMenu$BeatmapReloadThread.run(SongMenu.java:241)
```

**Comment by memebae** [comment]
Importing 86400 beatmap and JVM crashes despite my 96GB RAM

**Comment by Lemmmy** [comment]
Java starts with a limited amount of RAM allocated by default; try allocating more with the -Xmx argument, e.g. `java -Xmx 8G -jar opsu.jar`

**Comment by memebae** [comment]
![image](https://user-images.githubusercontent.com/36472102/42877586-5d8682b0-8ac9-11e8-9789-e349436c7ee5.png)
Now it doesn't run...

**Comment by memebae** [comment]
without -Xmx argument, it starts.

**Comment by memebae** [comment]
-Xmx1G starts
-Xmx2G doesn't start
-Xmx4G throws fatal exception error window

**Comment by memebae** [comment]
Just noticed my Java is x86 not x64. My bad.
