### ISSUE TITLE
Game.render() failure.

### ISSUE THREAD

**Issue by Haringat** [itdelatrisu/opsu#412]
Always happens at a certain point around 1:07 in 642061 EGOIST - Eiyuu Unmei no Uta.

**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Linux (amd64)
**JRE:** 1.8.0_161
**OpenGL version:** 4.6.0 NVIDIA 390.59 (NVIDIA Corporation)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at itdelatrisu.opsu.render.CurveRenderState.renderCurve(CurveRenderState.java:456)
	at itdelatrisu.opsu.render.CurveRenderState.draw(CurveRenderState.java:125)
	at itdelatrisu.opsu.objects.curves.Curve.draw(Curve.java:156)
	at itdelatrisu.opsu.objects.Slider.draw(Slider.java:221)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1741)
	at itdelatrisu.opsu.states.Game.render(Game.java:671)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```

**Comment by Haringat** [comment]
I just saw #297 and enabling experimental sliders did the trick
