### ISSUE TITLE
Game.render() failure.       plz fix it ;-;

### ISSUE THREAD

**Issue by Numder02** [itdelatrisu/opsu#417]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_131
**OpenGL version:** 4.6.0 NVIDIA 391.35 (NVIDIA Corporation)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Unknown Source)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at org.lwjgl.BufferUtils.createByteBuffer(BufferUtils.java:60)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.createVertexBuffer(LegacyCurveRenderState.java:308)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.initFBO(LegacyCurveRenderState.java:128)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.<init>(LegacyCurveRenderState.java:118)
	at itdelatrisu.opsu.objects.curves.FakeCombinedCurve.draw(FakeCombinedCurve.java:63)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1706)
	at itdelatrisu.opsu.states.Game.render(Game.java:671)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```

**Comment by Lemmmy** [comment]
You ran out of memory - try allocating more memory to the JVM with `java -Xmx 2G -jar opsu!.jar`.

**Comment by itdelatrisu** [comment]
How many beatmaps did you have loaded?
