### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by buyaoshushu** [itdelatrisu/opsu#418]
**Version:** 0.16.1
**Build date:** 2018-06-13 01:54
**OS:** Linux (amd64)
**JRE:** 1.8.0_181
**OpenGL version:** 3.0 Mesa 18.1.5 (Intel Open Source Technology Center)
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NoSuchMethodError: java.nio.FloatBuffer.flip()Ljava/nio/FloatBuffer;
	at org.newdawn.slick.openal.SoundStore.init(SoundStore.java:376)
	at org.newdawn.slick.Music.<init>(Music.java:204)
	at itdelatrisu.opsu.audio.MusicController.loadTrack(MusicController.java:144)
	at itdelatrisu.opsu.audio.MusicController.access$000(MusicController.java:54)
	at itdelatrisu.opsu.audio.MusicController$1.run(MusicController.java:116)
```

**Comment by tpenguinltg** [comment]
This sounds like a version problem, but I can't imagine why. Are you using the Oracle JRE or the OpenJDK JRE?

**Comment by itdelatrisu** [comment]
Going to merge this into #421 since that has more details.
