### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by Haringat** [itdelatrisu/opsu#421]
**Version:** 0.16.1
**Build date:** 2018-08-08 00:33
**OS:** Linux (amd64)
**JRE:** 1.8.0_181
**OpenGL version:** 4.6.0 NVIDIA 396.45 (NVIDIA Corporation)
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NoSuchMethodError: java.nio.FloatBuffer.flip()Ljava/nio/FloatBuffer;
	at org.newdawn.slick.openal.SoundStore.init(SoundStore.java:376)
	at org.newdawn.slick.Music.<init>(Music.java:204)
	at itdelatrisu.opsu.audio.MusicController.loadTrack(MusicController.java:144)
	at itdelatrisu.opsu.audio.MusicController.access$000(MusicController.java:54)
	at itdelatrisu.opsu.audio.MusicController$1.run(MusicController.java:116)
```

This happens on Java SE 8 JDK as well as OpenJDK8 when trying to access the main menu. It does not happen on Java9+ though.

**Comment by tpenguinltg** [comment]
Duplicate of #418. I still don't understand how this is triggered because I'm on Java 8 and I don't get this error, both with sound effects on and off.

**Comment by itdelatrisu** [comment]
Linking #418.

**Comment by Lyonlancer5** [comment]
Java 9+?
May be related to https://github.com/plasma-umass/doppio/issues/497, specifically [this](https://github.com/plasma-umass/doppio/issues/497#issuecomment-314842089) and [this](https://github.com/plasma-umass/doppio/issues/497#issuecomment-334740243).

Noting that `FloatBuffer` and `ByteBuffer` both extend `Buffer`, the signature `java.nio.FloatBuffer.flip()Ljava/nio/FloatBuffer;` seems to expect a return type of a `FloatBuffer` instead of the superclass' `Buffer` [(javadoc referenced)](https://docs.oracle.com/javase/7/docs/api/java/nio/Buffer.html#flip()).

~~Could it be that the JDK used to build the JARs are JDK 9+ targeting JDK 7 compatibility?~~

**Comment by tpenguinltg** [comment]
> ~Could it be that the JDK used to build the JARs are JDK 9+ targeting JDK 7 compatibility?~
No, not for the JARs, but based on the build date, it looks like @Haringat is building it himself.

@Haringat: I trust that running `javac -version` shows a Java 8 version?

I pushed up an [`issue/421`](https://github.com/tpenguinltg/opsu/tree/issue/421) branch on my fork with the workaround described in the links above. Can you please try building from that branch (or apply [the diff](https://github.com/itdelatrisu/opsu/compare/master...tpenguinltg:issue/421.diff) yourself) and see if that fixes anything?

**Comment by tpenguinltg** [comment]
@amaothree Are you building it yourself or using the JAR?
