### ISSUE TITLE
Game.update() failure.

### ISSUE THREAD

**Issue by kabessao** [itdelatrisu/opsu#432]
**Version:** 0.16.1
**Build date:** 2018-09-01 02:28
**OS:** Linux (amd64)
**JRE:** 1.8.0_181
**OpenGL version:** 3.0 Mesa 18.1.7 (Intel Open Source Technology Center)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Caused by: java.lang.NullPointerException
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1752)
	at itdelatrisu.opsu.states.DownloadsMenu.update(DownloadsMenu.java:563)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:266)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	... 3 more
```

**Comment by tpenguinltg** [comment]
Do you know which map you downloaded to cause this error?
