### ISSUE TITLE
Game.render() failure. (i was playing an osu! aspire map and the game crashed)

### ISSUE THREAD

**Issue by Matheus-programer** [itdelatrisu/opsu#436]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_131
**OpenGL version:** 4.6.0 NVIDIA 391.35 (NVIDIA Corporation)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at itdelatrisu.opsu.render.CurveRenderState.renderCurve(CurveRenderState.java:456)
	at itdelatrisu.opsu.render.CurveRenderState.draw(CurveRenderState.java:125)
	at itdelatrisu.opsu.objects.curves.Curve.draw(Curve.java:156)
	at itdelatrisu.opsu.objects.Slider.draw(Slider.java:221)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1741)
	at itdelatrisu.opsu.states.Game.render(Game.java:671)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```

**Comment by tpenguinltg** [comment]
Linking #297. Probably a duplicate.

**Comment by tpenguinltg** [comment]
It may be a different map, but it's probably the same underlying problem. Thanks for letting us know what the beatmap is, though. It will be a great help in finding the problem. It's beatmap [#484689](https://osu.ppy.sh/beatmapsets/484689/), right?

**Comment by Matheus-programer** [comment]
@tpenguinltg yes
