### ISSUE TITLE
Game.render() failure.

### ISSUE THREAD

**Issue by Zhai2333** [itdelatrisu/opsu#441]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_181
**OpenGL version:** 4.6.0 NVIDIA 411.70 (NVIDIA Corporation)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at itdelatrisu.opsu.render.CurveRenderState.renderCurve(CurveRenderState.java:456)
	at itdelatrisu.opsu.render.CurveRenderState.draw(CurveRenderState.java:125)
	at itdelatrisu.opsu.objects.curves.Curve.draw(Curve.java:156)
	at itdelatrisu.opsu.objects.Slider.draw(Slider.java:221)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1741)
	at itdelatrisu.opsu.states.Game.render(Game.java:671)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```

Cause by aspire maps (like aleph-0)

**Comment by tpenguinltg** [comment]
Probably a duplicate of #297. Can you please link us to a map that triggers this?
