### ISSUE TITLE
ERROR:line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.

### ISSUE THREAD

**Issue by Youboontoo** [itdelatrisu/opsu#442]
This error message interrupts me every single time I play past a certain part in Rameses B's "Flaklypa [Hard]:
`Mon Oct 01 15:35:35 PDT 2018 ERROR:Could not start a clip 'soft-hitwhistle.wav'.
Mon Oct 01 15:35:35 PDT 2018 ERROR:line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:503)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1292)
	at java.desktop/com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:119)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1074)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1041)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:213)
	at itdelatrisu.opsu.audio.MultiClip.start(MultiClip.java:135)
	at itdelatrisu.opsu.audio.SoundController.playClip(SoundController.java:312)
	at itdelatrisu.opsu.audio.SoundController.playHitSound(SoundController.java:359)
	at itdelatrisu.opsu.GameData.sendSliderTickResult(GameData.java:1448)
	at itdelatrisu.opsu.objects.Slider.update(Slider.java:720)
	at itdelatrisu.opsu.states.Game.updateGame(Game.java:1144)
	at itdelatrisu.opsu.states.Game.runReplayFrame(Game.java:2170)
	at itdelatrisu.opsu.states.Game.addReplayFrameAndRun(Game.java:2153)
	at itdelatrisu.opsu.states.Game.update(Game.java:876)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:266)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)`

**Comment by tpenguinltg** [comment]
Please tell us:
* opsu! version
* OS (if Linux, the distro as well)
* Java version
* OpenGL version (if you can)

If you're on opsu! version 0.16.1, you can click on the GitHub icon in the the bottom left and click on "Copy Debug Info"; when you click it, it should copy some info to your clipboard that you can paste here.

**Comment by Youboontoo** [comment]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Linux (amd64)
**JRE:** 10.0.2
**OpenGL version:** 4.6.0 NVIDIA 390.87 (NVIDIA Corporation)

I am using Ubuntu 18.04.1
