### ISSUE TITLE
game gives error message at end of each long slider

### ISSUE THREAD

**Issue by TT-392** [itdelatrisu/opsu#444]
I am playing opsu on arch linux (from the aur, I also tried opsu-git). And every time when I play a few specific maps the game pauses and gives the following error message:
https://pastebin.com/uMTRFEyx

after a bit of experimenting with this map and finding the same error happening at the same point, I figured out I could click away the error message and then get the same error after each long slider. I have encountered this problem in a few other maps in the past but I havent tried to experiment with those maps.

I seem to be able to reliably recreate the issue at the same point in a map called Classical Insanity from louis cyphre on the "Allegro" difficulty

**Comment by tpenguinltg** [comment]
I think this is the relevant error:
```
Mon Oct 15 23:40:27 CEST 2018 ERROR:Could not start a clip 'soft-slidertick.wav'.
Mon Oct 15 23:40:27 CEST 2018 ERROR:line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
    at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
    at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
    at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
    at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
    at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1052)
    at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:213)
    at itdelatrisu.opsu.audio.MultiClip.start(MultiClip.java:135)
    at itdelatrisu.opsu.audio.SoundController.playClip(SoundController.java:312)
    at itdelatrisu.opsu.audio.SoundController.playHitSound(SoundController.java:372)
    at itdelatrisu.opsu.GameData.sendSliderTickResult(GameData.java:1455)
    at itdelatrisu.opsu.objects.Slider.update(Slider.java:738)
    at itdelatrisu.opsu.states.Game.updateGame(Game.java:1144)
    at itdelatrisu.opsu.states.Game.runReplayFrame(Game.java:2170)
    at itdelatrisu.opsu.states.Game.addReplayFrameAndRun(Game.java:2153)
    at itdelatrisu.opsu.states.Game.update(Game.java:876)
    at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:266)
    at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
    at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
    at itdelatrisu.opsu.Container.start(Container.java:80)
    at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
```

This is likely a duplicate of the other [Linux audio issues](https://github.com/itdelatrisu/opsu/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Alinux+label%3Aaudio)

**Comment by TT-392** [comment]
this does indeed seem to be a duplicate of those issues. And it does seem like it probably has something to do with my sound setup. the most frustrating part seems to be that the error message appears but the game is fine. The game  seems to be perfectly playable if it wasn't for the error messages popping up.
I just tried it with a different openjdk version (10) which doesn't seem to fix anything. the wierd part  is that everything works fine when running as root.

**Comment by tpenguinltg** [comment]
> the wierd part is that everything works fine when running as root.
I'm guessing it's because root doesn't have any audio processes running, so it uses a different pool of lines. I suspect it's the same when running as any other user. Also, don't run the game as root.

If you're okay with no hitsounds until this gets resolved, you can turn them off in the options.

**Comment by TT-392** [comment]
I know I can turn off hitsounds but when I don't everything works, untill the error freezes the game, if you close the error box the game continues without a problem and as far as I can tell also with no sound effects missing. so if the errors were just ignored everything would be perfectly playable.

(I know I shouldn't run the game as root I just wanted to test if a different user would work)
