### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by MeguMario** [itdelatrisu/opsu#451]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Linux (amd64)
**JRE:** 1.8.0_181
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.ExceptionInInitializerError
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:195)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.XRandR.findPrimary(XRandR.java:326)
	at org.lwjgl.opengl.XRandR.ScreentoDisplayMode(XRandR.java:315)
	at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:746)
	at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:743)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:743)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 4 more
```

**Comment by ScoreUnder** [comment]
Can you also paste the output of the `xrandr` command?

I'm not a member of this project, nor do I think this is a bug in opsu (it's almost definitely a lwjgl bug), but with that information the solution (or at least a workaround) might be clearer.

**Comment by tpenguinltg** [comment]
Duplicate of #427? There's #434 to address it, but it hasn't been looked at yet.

@MeguMario when do you see this error and how often?

**Comment by MeguMario** [comment]
> Duplicate of #427? There's #434 to address it, but it hasn't been looked at yet.
> 
> @MeguMario when do you see this error and how often?

well, it only happen when i ran the game while using vga output, internal screen and hdmi work fine
