### ISSUE TITLE
openjdk8u doesn't start Opsu

### ISSUE THREAD

**Issue by user5145** [itdelatrisu/opsu#454]
Opsu doesn't start with openjdk8u, but works fine with oracle java and openjdk9+

How to reproduce:
It should be enough to download openjdk8u from adoptopenjdk.net and try to use it. I was able to reproduce it within flatpak sandbox.

---
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Linux (amd64)
**JRE:** 1.8.0_192-b12 and jdk8u172-b11
**OpenGL version:** 4.6.0 NVIDIA 410.73 (NVIDIA Corporation)
OS: Arch
Kernel: 4.19.1

Error: Uncaught Exception (NullPointerException and IOException)
Stack trace:

Fri Nov 16 17:40:14 CET 2018 ERROR:Failed to load fonts.
Fri Nov 16 17:40:14 CET 2018 ERROR:Problem reading font data.
java.io.IOException: Problem reading font data.
	at java.awt.Font.createFont0(Font.java:1000)
	at java.awt.Font.createFont(Font.java:877)
	at itdelatrisu.opsu.ui.Fonts.init(Fonts.java:59)
	at itdelatrisu.opsu.Utils.init(Utils.java:145)
	at itdelatrisu.opsu.states.Splash.init(Splash.java:105)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:171)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
	at itdelatrisu.opsu.Container.runSetup(Container.java:112)
	at itdelatrisu.opsu.Container.start(Container.java:77)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Fri Nov 16 17:40:14 CET 2018 ERROR:null
java.lang.NullPointerException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
	at sun.font.SunFontManager$2.run(SunFontManager.java:431)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.text.WrappedPlainView.updateMetrics(WrappedPlainView.java:318)
	at javax.swing.text.WrappedPlainView.updateChildren(WrappedPlainView.java:297)
	at javax.swing.text.WrappedPlainView.insertUpdate(WrappedPlainView.java:463)
	at javax.swing.plaf.basic.BasicTextUI$RootView.insertUpdate(BasicTextUI.java:1610)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(BasicTextUI.java:1869)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.JTextArea.append(JTextArea.java:477)
	at itdelatrisu.opsu.ErrorHandler.error(ErrorHandler.java:117)
	at itdelatrisu.opsu.Utils.init(Utils.java:147)
	at itdelatrisu.opsu.states.Splash.init(Splash.java:105)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:171)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
	at itdelatrisu.opsu.Container.runSetup(Container.java:112)
	at itdelatrisu.opsu.Container.start(Container.java:77)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Fri Nov 16 17:40:14 CET 2018 ERROR:** Uncaught Exception! **
Fri Nov 16 17:40:14 CET 2018 ERROR:null
java.lang.NullPointerException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
	at sun.font.SunFontManager$2.run(SunFontManager.java:431)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.text.WrappedPlainView.updateMetrics(WrappedPlainView.java:318)
	at javax.swing.text.WrappedPlainView.updateChildren(WrappedPlainView.java:297)
	at javax.swing.text.WrappedPlainView.removeUpdate(WrappedPlainView.java:485)
	at javax.swing.plaf.basic.BasicTextUI$RootView.removeUpdate(BasicTextUI.java:1624)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.removeUpdate(BasicTextUI.java:1884)
	at javax.swing.text.AbstractDocument.fireRemoveUpdate(AbstractDocument.java:259)
	at javax.swing.text.AbstractDocument.handleRemove(AbstractDocument.java:622)
	at javax.swing.text.AbstractDocument.remove(AbstractDocument.java:590)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:666)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1669)
	at itdelatrisu.opsu.ErrorHandler.error(ErrorHandler.java:115)
	at itdelatrisu.opsu.Container.start(Container.java:96)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)

**Comment by tpenguinltg** [comment]
Were you able to reproduce this outside of flatpak? If not, it might be a problem with your flatpak configuration.

**Comment by user5145** [comment]
Sorry for the late reply.

Yes it occurs both with and without flatpak. I didn't change anything. Everything was done normally when i tested it on my system.

**Comment by user5145** [comment]
ok. a few days ago I got rid of arch and now i'm 90% opensuse, 10% windows, so I tested it once more and this error is gone. I used jdk8u202-b08 and jdk8u192-b12  to test it (it works) and I don't longer can test it in arch. It can be just that this error has something to do with my arch setup, arch in general or some windows/google's fonts I had installed before.
