### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by Nomby** [itdelatrisu/opsu#460]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_191
**OpenGL version:** 4.5.13537 Compatibility Profile Context 24.20.13001.1010 (ATI Technologies Inc.)
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.OutOfMemoryError: Java heap space
	at itdelatrisu.opsu.audio.MultiClip.<init>(MultiClip.java:106)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:140)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:100)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:234)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```

**Comment by Nomby** [comment]
I don´t know whats happening here :c
