### ISSUE TITLE
Game.render() failure.

### ISSUE THREAD

**Issue by 46620** [itdelatrisu/opsu#470]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_201
**OpenGL version:** 4.6.0 NVIDIA 419.17 (NVIDIA Corporation)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at itdelatrisu.opsu.render.CurveRenderState.renderCurve(CurveRenderState.java:456)
	at itdelatrisu.opsu.render.CurveRenderState.draw(CurveRenderState.java:125)
	at itdelatrisu.opsu.objects.curves.Curve.draw(Curve.java:156)
	at itdelatrisu.opsu.objects.Slider.draw(Slider.java:221)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1741)
	at itdelatrisu.opsu.states.Game.render(Game.java:671)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```

**Comment by tpenguinltg** [comment]
@46620 Do you remember which map triggered this error?

**Comment by 46620** [comment]
@tpenguinltg https://osu.ppy.sh/beatmapsets/855677#osu/1787848
