### ISSUE TITLE
The databases could not be initialized.

### ISSUE THREAD

**Issue by roro47** [itdelatrisu/opsu#471]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Linux (amd64)
**JRE:** 10.0.2
**Error:** `The databases could not be initialized.`
**Stack trace:**
```
org.sqlite.SQLiteException: [SQLITE_CANTOPEN]  Unable to open the database file (unable to open database file)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
	at org.sqlite.core.DB.prepare(DB.java:227)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:81)
	at itdelatrisu.opsu.db.BeatmapDB.updateDatabase(BeatmapDB.java:214)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:139)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:40)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:123)
```

**Comment by itdelatrisu** [comment]
This is probably a system related issue. Haven't seen this error before.
