### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by KaoGomi** [itdelatrisu/opsu#473]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Linux (amd64)
**JRE:** 11.0.1
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:472)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:488)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:532)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:613)
	at org.lwjgl.LinuxSysImplementation.<clinit>(LinuxSysImplementation.java:50)
	at org.lwjgl.Sys.createImplementation(Sys.java:131)
	at org.lwjgl.Sys.<clinit>(Sys.java:116)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:195)
Caused by: java.lang.ClassNotFoundException: org.GNOME.Accessibility.AtkWrapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:485)
	... 19 more
```

So, what could I possibly do to correct this issue?

**Comment by KaoGomi** [comment]
When I comment out the 'assistive_technologies=org.GNOME.Accessibility.AtkWrapper' in my 'java-11-openjdk/accessiblity.properties', I get:
```Inconsistency detected by ld.so: dl-lookup.c: 112: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed! ```

Is this an issue with the OpenJDK version? I've tried using older OpenJDK versions with no better results. I've even gone as far as compiling it from the source, but it didn't get me much further.

**Comment by itdelatrisu** [comment]
Linking #468.

**Comment by tpenguinltg** [comment]
@KaoGomi Try this:

>This can be done by editing the accessibility.properties file for OpenJDK:  
>`sudo vim /etc/java-8-openjdk/accessibility.properties`  
>Comment out the following line:  
>`assistive_technologies=org.GNOME.Accessibility.AtkWrapper`

https://askubuntu.com/a/723503
https://github.com/Microsoft/vscode-arduino/issues/644#issuecomment-415329398

**Comment by JohnnyLAmpAz** [comment]
I commented by mistake on closed issue https://github.com/itdelatrisu/opsu/issues/468#issuecomment-787522330

**Comment by hyphen-four** [comment]
I am also having this issue on Debian 11, is there any way I can at least work around this? I want to try osu! but it doesn't run natively on Linux, so this is the only option I've found 🙁
