### ISSUE TITLE
Game.render() failure.

### ISSUE THREAD

**Issue by Hayndy** [itdelatrisu/opsu#474]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 7 (x86)
**JRE:** 1.8.0_201
**OpenGL version:** 1.4.0 - Build 8.14.10.1930 (Intel)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Caused by: java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.EXTFramebufferObject.glGenFramebuffersEXT(EXTFramebufferObject.java:244)
	at itdelatrisu.opsu.render.Rendertarget.<init>(Rendertarget.java:55)
	at itdelatrisu.opsu.render.Rendertarget.createRTTFramebuffer(Rendertarget.java:110)
	at itdelatrisu.opsu.render.FrameBufferCache.insert(FrameBufferCache.java:119)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.initFBO(LegacyCurveRenderState.java:126)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.<init>(LegacyCurveRenderState.java:118)
	at itdelatrisu.opsu.objects.curves.FakeCombinedCurve.draw(FakeCombinedCurve.java:63)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1706)
	at itdelatrisu.opsu.states.Game.render(Game.java:671)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```

**Comment by itdelatrisu** [comment]
The game requires OpenGL 2.0 at the very minimum (3.0+ for real slider rendering).
