### ISSUE TITLE
Failed to initialise the LWJGL display

### ISSUE THREAD

**Issue by Kingl123** [itdelatrisu/opsu#486]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_211
**Stack trace:**
```
org.newdawn.slick.SlickException: Failed to initialise the LWJGL display
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:378)
	at itdelatrisu.opsu.Container.runSetup(Container.java:118)
	at itdelatrisu.opsu.Container.start(Container.java:77)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
```

**Comment by CFP-PC20** [comment]
Same here, using Arch with Nvidia drivers. Any fix?
**Version:** 0.16.1
**Build date:** 2019-11-10 00:04
**OS:** Linux (amd64)
**JRE:** 1.8.0_232
