### ISSUE TITLE
null

### ISSUE THREAD

**Issue by Till-Brinkmann** [itdelatrisu/opsu#487]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (amd64)
**JRE:** 10.0.1
**OpenGL version:** 4.6.13544 Compatibility Profile Context 25.20.15011.1004 (ATI Technologies Inc.)
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.objects.curves.Vec2f.sub(Vec2f.java:90)
	at itdelatrisu.opsu.beatmap.tpHitObject.distanceTo(BeatmapDifficultyCalculator.java:500)
	at itdelatrisu.opsu.beatmap.tpHitObject.calculateSpecificStrain(BeatmapDifficultyCalculator.java:470)
	at itdelatrisu.opsu.beatmap.tpHitObject.calculateStrains(BeatmapDifficultyCalculator.java:416)
	at itdelatrisu.opsu.beatmap.BeatmapDifficultyCalculator.calculateStrainValues(BeatmapDifficultyCalculator.java:214)
	at itdelatrisu.opsu.beatmap.BeatmapDifficultyCalculator.calculate(BeatmapDifficultyCalculator.java:149)
	at itdelatrisu.opsu.states.SongMenu.calculateStarRatings(SongMenu.java:1973)
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1752)
	at itdelatrisu.opsu.states.SongMenu.moveFocus(SongMenu.java:1644)
	at itdelatrisu.opsu.states.SongMenu.keyPressed(SongMenu.java:1276)
	at org.newdawn.slick.state.StateBasedGame.keyPressed(StateBasedGame.java:445)
	at org.newdawn.slick.Input.poll(Input.java:1197)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
```

**Comment by Till-Brinkmann** [comment]
Im not very familiar with the code of this project, but after having a quick look at the methods in the stackdump of the error it seems like it was caused by normalizedEndPosition being null which means
baseHitObject.getRepeatCount() in the constructor is 0.

**Comment by Till-Brinkmann** [comment]
One of the beatmaps it happens on is 360610 Sasai Ryuji - Shinsen which i also can not load in normal osu so seems like it's an issue with corrupted beatmaps
