### ISSUE TITLE
Game.render() failure.

### ISSUE THREAD

**Issue by propelling** [itdelatrisu/opsu#492]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_212
**OpenGL version:** 4.6.0 NVIDIA 417.35 (NVIDIA Corporation)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Caused by: java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Unknown Source)
	at java.nio.DirectFloatBufferU.put(Unknown Source)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.fillCone(LegacyCurveRenderState.java:394)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.createVertexBuffer(LegacyCurveRenderState.java:314)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.initFBO(LegacyCurveRenderState.java:128)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.<init>(LegacyCurveRenderState.java:118)
	at itdelatrisu.opsu.objects.curves.FakeCombinedCurve.draw(FakeCombinedCurve.java:63)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1706)
	at itdelatrisu.opsu.states.Game.render(Game.java:671)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```
**Some information, added by me regarding this:**
I decided to test your client's performance with some sh*tmaps; [one of them](https://drive.google.com/open?id=1TTrfcpF8tNfEeztiLNfZyF-fpyEOfrH_) (using a google drive link because osu! nuked earrape beatmaps) caused the client to crash before the game started.

**Comment by DarioTD** [comment]
try reinstalling java or updating it to a new version

**Comment by yugecin** [comment]
> try reinstalling java or updating it to a new version

this has little to nothing to do with the java installation
