### ISSUE TITLE
Uncaught Exception! - Arco Linux OS

### ISSUE THREAD

**Issue by Rin-Tadashi** [itdelatrisu/opsu#502]
**_Hello , running on the following laptop:_**
**OS:** ArcoLinuxD v19.06.1 
**Kernel:** 5.3.7-arch1-1-ARCH 
**Resolution:** 1366x768 
**CPU:** Intel i5-4200H (4) @ 3.400GHz 
**GPU:** NVIDIA GeForce GTX 950M 
**GPU:** Intel 4th Gen Core Processor 
**Memory:** 7853MiB 

**_I received the following error upon startup:_**

ERROR:** Uncaught Exception! **
ERROR:java.nio.FloatBuffer.flip()Ljava/nio/FloatBuffer;
java.lang.NoSuchMethodError: java.nio.FloatBuffer.flip()Ljava/nio/FloatBuffer;
	at org.newdawn.slick.openal.SoundStore.init(SoundStore.java:376)
	at org.newdawn.slick.Music.<init>(Music.java:204)
	at itdelatrisu.opsu.audio.MusicController.loadTrack(MusicController.java:144)
	at itdelatrisu.opsu.audio.MusicController.access$000(MusicController.java:54)
	at itdelatrisu.opsu.audio.MusicController$1.run(MusicController.java:116)

**_Any way to fix this issue?_**

**Comment by nonetrix** [comment]
same here seems to be nvidia problem 



fuck nvidia

**Comment by flleeppyy** [comment]
i see, other people are having the same problem. thing is, i dont even have a nvidia graphics card.

**Comment by CloneWith** [comment]
NVIDIA shouldn't be blamed for this.
This is just an audio initialization error, which is relatively common among Linux devices.

**Comment by nonetrix** [comment]
Yeah idk what I was smoking tbh

**Comment by nonetrix** [comment]
I could try this again on AMD GPU, but highly doubtful it was NVIDIA. Not sure where I got that idea from I don't even think I read the error kek. But Osu Lazer is way better anyway, so I would just use that
