### ISSUE TITLE
No line matching interface Clip supporting format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian is supported.

### ISSUE THREAD

**Issue by Cata1508** [itdelatrisu/opsu#518]
**Version:** 0.16.0
**Build date:** 2017-07-02 17:27
**OS:** Linux (i386)
**JRE:** 1.8.0_73
**OpenGL version:** 2.1 Mesa 19.2.8 (Intel Open Source Technology Center)
**Stack trace:**
```
java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian is supported.
	at javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:479)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:211)
	at itdelatrisu.opsu.audio.MultiClip.start(MultiClip.java:135)
	at itdelatrisu.opsu.audio.SoundController.playClip(SoundController.java:308)
	at itdelatrisu.opsu.audio.SoundController.playSound(SoundController.java:320)
	at itdelatrisu.opsu.states.MainMenu.mousePressed(MainMenu.java:824)
	at org.newdawn.slick.state.StateBasedGame.mousePressed(StateBasedGame.java:499)
	at org.newdawn.slick.Input.poll(Input.java:1241)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
```

**Comment by JordanPlayz158** [comment]
If anyone knows, this would be much appreciated, I am having this issue as well!
