### ISSUE TITLE
Invalid data found on audio file 'C:\Users\user\AppData\Local\osu!\Skins\#User\drum-slidertick.wav'.

### ISSUE THREAD

**Issue by TYTheBeast** [itdelatrisu/opsu#529]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (amd64)
**JRE:** 14.0.1
**OpenGL version:** 4.6.0 NVIDIA 445.87 (NVIDIA Corporation)
**Error:** `Invalid data found on audio file 'C:\Users\user\AppData\Local\osu!\Skins\#User\drum-slidertick.wav'.`
**Stack trace:**
```
javax.sound.sampled.UnsupportedAudioFileException: URL of unsupported format
	at java.desktop/javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1040)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:99)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:255)
	at itdelatrisu.opsu.states.Splash$1.run(Splash.java:138)
```

**Comment by kairusds** [comment]
change the skin's directory

**Comment by madiqe** [comment]
Close this
