### ISSUE TITLE
Game.update() failure.

### ISSUE THREAD

**Issue by legendtang** [itdelatrisu/opsu#53]
**Version:** 0.7.0
**Build date:** 2015-03-19 08:44
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:93)
	at itdelatrisu.opsu.Container.start(Container.java:67)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:165)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at itdelatrisu.opsu.objects.curves.LinearBezier.<init>(LinearBezier.java:141)
	at itdelatrisu.opsu.objects.Slider.<init>(Slider.java:141)
	at itdelatrisu.opsu.states.Game.enter(Game.java:756)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	... 3 more
```

**Comment by itdelatrisu** [comment]
Thanks for the report.  Do you know which map causes this?  @fluddokt, do you mind having a look?

**Comment by legendtang** [comment]
Hi @itdelatrisu,

It's this [map](http://osu.ppy.sh/s/160493) that caused the issue.

Regards

**Comment by chong601** [comment]
Extra add on: Only affects "Daybreak" difficulty, other diffs are unaffected
