### ISSUE TITLE
Failed to prepare score statements.

### ISSUE THREAD

**Issue by xasuma** [itdelatrisu/opsu#55]
**Version:** 0.7.0
**Build date:** 2015-03-09 00:40
**Error:** `Failed to prepare score statements.`
**Stack trace:**
```
java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (table scores has 18 columns but 17 values were supplied)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.throwex(DB.java:868)
	at org.sqlite.core.NativeDB.prepare(Native Method)
	at org.sqlite.core.DB.prepare(DB.java:211)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:251)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:223)
	at itdelatrisu.opsu.db.ScoreDB.init(ScoreDB.java:71)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:47)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:138)
```

**Comment by chong601** [comment]
Did you happen to open 0.8.0 and then try opening 0.7.0 back? That may cause this problem since it seems that the score db format has been changed on 0.8.0 and make it incompatible with 0.7.0

**Comment by itdelatrisu** [comment]
Yes, that was the problem (discussed on the osu! forum thread).
