### ISSUE TITLE
Invalid data found on audio file '/home/ares/Games/osu/Skins/Gawr Gura/readys.wav'.

### ISSUE THREAD

**Issue by Lionshide** [itdelatrisu/opsu#557]
I'm trying to use other skin, but this happened. I don't know

**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Linux (amd64)
**JRE:** 1.8.0_73
**OpenGL version:** 4.6 (Compatibility Profile) Mesa 20.3.1 (Intel)
**Error:** `Invalid data found on audio file '/home/ares/Games/osu/Skins/Gawr Gura/readys.wav'.`
**Stack trace:**
```
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1155)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:99)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:234)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```

**Comment by CloneWith** [comment]
Could this audio file be played properly on your device? Since chances are that the file is corrupt, try opening it with a random audio player first.
