### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by xasuma** [itdelatrisu/opsu#56]
**Version:** 0.7.0
**Build date:** 2015-03-09 00:40
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.db.ScoreDB.closeConnection(ScoreDB.java:286)
	at itdelatrisu.opsu.db.DBController.closeConnections(DBController.java:55)
	at itdelatrisu.opsu.Opsu.close(Opsu.java:227)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:169)
```

**Comment by chong601** [comment]
Possibly related to #55?
