### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by Iori-yimaga** [itdelatrisu/opsu#561]
**Version:** 0.16.1
**Build date:** 2018-06-13 01:54
**OS:** Linux (amd64)
**JRE:** 1.8.0_282
**OpenGL version:** 4.6 (Compatibility Profile) Mesa 20.3.4 (Intel)
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NoSuchMethodError: java.nio.FloatBuffer.flip()Ljava/nio/FloatBuffer;
	at org.newdawn.slick.openal.SoundStore.init(SoundStore.java:376)
	at org.newdawn.slick.Music.<init>(Music.java:204)
	at itdelatrisu.opsu.audio.MusicController.loadTrack(MusicController.java:144)
	at itdelatrisu.opsu.audio.MusicController.access$000(MusicController.java:54)
	at itdelatrisu.opsu.audio.MusicController$1.run(MusicController.java:116)
```

**Comment by with9** [comment]
It may be a problem with the java version. try to install java10,and modify /usr/bin/opsu, specifying the java version.
the opsu will be something like this
```shell
exec /usr/lib/jvm/java-10-openjdk/bin/java -jar '/usr/share/java/opsu/opsu.jar' "$@"
```
