### ISSUE TITLE
Game.update() failure.

### ISSUE THREAD

**Issue by xasuma** [itdelatrisu/opsu#57]
**Version:** 0.7.0
**Build date:** 2015-03-09 00:40
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:93)
	at itdelatrisu.opsu.Container.start(Container.java:67)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:165)
Caused by: java.lang.NullPointerException
	at itdelatrisu.opsu.db.ScoreDB.getMapSetScores(ScoreDB.java:241)
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1177)
	at itdelatrisu.opsu.states.SongMenu.enter(SongMenu.java:923)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	... 3 more
```

**Comment by chong601** [comment]
Also possibly related to #55
