### ISSUE TITLE
** Uncaught Exception! ** opsu! doesn't launch

### ISSUE THREAD

**Issue by KotTheKitty** [itdelatrisu/opsu#588]
# This is the error I get when trying to launch opsu!

**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_261
**OpenGL version:** 4.4.0 - Build 20.19.15.4835 (Intel)
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.UnsatisfiedLinkError: C:\Users\turn02\AppData\Local\Temp\jna--1809099969\jna4363260712825260443.dll: %1 n’est pas une application Win32 valide
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1086)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
	at com.sun.jna.Native.<clinit>(Native.java:140)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
	at com.sun.jna.platform.win32.WinReg$HKEY.<init>(WinReg.java:32)
	at com.sun.jna.platform.win32.WinReg.<clinit>(WinReg.java:61)
	at itdelatrisu.opsu.options.Options.getOsuInstallationDirectory(Options.java:211)
	at itdelatrisu.opsu.options.Options.getSkinRootDir(Options.java:1492)
	at itdelatrisu.opsu.options.Options.getSkinDir(Options.java:1545)
	at itdelatrisu.opsu.options.Options.loadSkin(Options.java:1511)
	at itdelatrisu.opsu.Utils.init(Utils.java:151)
	at itdelatrisu.opsu.states.Splash.init(Splash.java:105)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:171)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
	at itdelatrisu.opsu.Container.runSetup(Container.java:112)
	at itdelatrisu.opsu.Container.start(Container.java:77)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
```

**Comment by MFDaus47** [comment]
Hey, unfortunately to say this project has been quite dead, so there's surely a lot of bugs and problem. If you actually want to try this app, you can try the phone version on play store( it has bugs too). Or maybe try OSU! Which is the actual app that this app is sampling from. This app is practically similar in terms of gameplay. also, OSU! Is still maintained and very active in bug fixing. Here's the link : osu.ppy.sh

**Comment by udu3324** [comment]
In this line, it seems like opsu has a file that only supports 64 bit machines only.
`java.lang.UnsatisfiedLinkError: C:\Users\turn02\AppData\Local\Temp\jna--1809099969\jna4363260712825260443.dll: %1 n’est pas une application Win32 valide
`
Basicly, the error says that jna4363260712825260443.dll is not a valid Win32 application.
What you can basicly do is just get a 64 bit pc or play the real osu.

**Comment by KotTheKitty** [comment]
Back when I was having this error, I was using the school computer with a portable Java version, which happened to be 32-bits. I do not have this error anymore because school is done (we are in august).
