### ISSUE TITLE
Failed to load file '/preview/278395.mp3'.

### ISSUE THREAD

**Issue by DuloT34** [itdelatrisu/opsu#59]
**Version:** 0.8.0
**Build date:** 2015-03-20 04:45
**OS:** Linux (amd64)
**JRE:** 1.7.0_75
**Error:** `Failed to load file '/preview/278395.mp3'.`
**Stack trace:**
```
java.lang.IllegalArgumentException: Invalid format
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:142)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:99)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:283)
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:164)
	at itdelatrisu.opsu.audio.MultiClip.<init>(MultiClip.java:94)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:118)
	at itdelatrisu.opsu.audio.SoundController.playTrack(SoundController.java:336)
	at itdelatrisu.opsu.states.DownloadsMenu$2.run(DownloadsMenu.java:488)
```

**Comment by itdelatrisu** [comment]
Does this happen for every beatmap you try to preview, or only sometimes?

**Comment by DuloT34** [comment]
Only sometimes.

**Comment by itdelatrisu** [comment]
Should be fixed -- it might have just been trying to play an incomplete file, and for some reason that exception wasn't being handled.
