### ISSUE TITLE
Failed to load file '/preview/163126.mp3'.

### ISSUE THREAD

**Issue by SimonJacobs** [itdelatrisu/opsu#60]
**Version:** 0.8.0
**Build date:** 2015-03-20 04:45
**OS:** Linux (amd64)
**JRE:** 1.7.0_75
**Error:** `Failed to load file '/preview/163126.mp3'.`
**Stack trace:**
```
java.lang.IllegalArgumentException: Invalid format
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:142)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:99)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:283)
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:164)
	at itdelatrisu.opsu.audio.MultiClip.<init>(MultiClip.java:94)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:118)
	at itdelatrisu.opsu.audio.SoundController.playTrack(SoundController.java:336)
	at itdelatrisu.opsu.states.DownloadsMenu$2.run(DownloadsMenu.java:488)
```

**Comment by itdelatrisu** [comment]
This is probably the same issue as #59, and I've already committed a fix (which you'll see in the next release).  Sorry for the inconvenience!
