### ISSUE TITLE
Game.render() failure.

### ISSUE THREAD

**Issue by AratnitY** [itdelatrisu/opsu#62]
(Was updating the map database after downloading about 6 maps in a row)

**Version:** 0.8.0
**Build date:** 2015-03-20 04:45
**OS:** Windows 8.1 (amd64)
**JRE:** 1.8.0_31
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:93)
	at itdelatrisu.opsu.Container.start(Container.java:67)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:169)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at itdelatrisu.opsu.downloads.DownloadList.getNode(DownloadList.java:61)
	at itdelatrisu.opsu.states.DownloadsMenu.render(DownloadsMenu.java:303)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```

**Comment by itdelatrisu** [comment]
Thanks for catching this; the fix will be included in the next release.  I think it was caused by the beatmap import thread clearing the download list while `render()` was drawing the downloads (or something similar), and I keep forgetting to check for these cases...  Sorry for the inconvenience.
