### ISSUE TITLE
Fri Jan 28 18:03:03 PST 2022 WARN:Failed to start download.

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [itdelatrisu/opsu#622]
I got an error when playing opsu.....
This was non-fatal.
```
org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)

```
```
Fri Jan 28 18:03:03 PST 2022 WARN:Failed to start download.
java.io.IOException: Server returned HTTP response code: 403 for URL: http://b.ppy.sh/preview/0.mp3
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:277)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://b.ppy.sh/preview/0.mp3
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:232)
Fri Jan 28 18:03:04 PST 2022 WARN:Failed to start download.
java.io.IOException: Server returned HTTP response code: 403 for URL: http://b.ppy.sh/preview/0.mp3
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:277)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://b.ppy.sh/preview/0.mp3
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:232)
Fri Jan 28 18:04:19 PST 2022 WARN:Failed to start download.
java.io.IOException: Server returned HTTP response code: 403 for URL: http://b.ppy.sh/preview/98375.mp3
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:277)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://b.ppy.sh/preview/98375.mp3
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:232)
Fri Jan 28 18:08:29 PST 2022 WARN:Failed to start download.
java.io.IOException: Server returned HTTP response code: 403 for URL: http://b.ppy.sh/preview/0.mp3
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:277)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://b.ppy.sh/preview/0.mp3
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:232)
Fri Jan 28 18:09:16 PST 2022 ERROR:Game.update() failure.
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Caused by: java.lang.NullPointerException
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1752)
	at itdelatrisu.opsu.states.DownloadsMenu.update(DownloadsMenu.java:563)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:266)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	... 3 more
Sat Jan 29 02:15:35 PST 2022 WARN:Failed to start download.
java.io.IOException: Server returned HTTP response code: 406 for URL: https://storage.ripple.moe/d/873741
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:277)
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: https://storage.ripple.moe/d/873741
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:232)
Sat Jan 29 02:15:52 PST 2022 WARN:Failed to start download.
java.io.IOException: Server returned HTTP response code: 406 for URL: https://storage.ripple.moe/d/873741
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:277)
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: https://storage.ripple.moe/d/873741
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at itdelatrisu.opsu.downloads.Download$1.run(Download.java:232)
Sat Jan 29 15:07:33 PST 2022 ERROR:Could not start a clip '/home/yusufkhan/Games/osu/Skins/osu!Default Skin/soft-hitnormal.wav'.
Sat Jan 29 15:07:33 PST 2022 ERROR:line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1052)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:213)
	at itdelatrisu.opsu.audio.MultiClip.start(MultiClip.java:135)
	at itdelatrisu.opsu.audio.SoundController.playClip(SoundController.java:312)
	at itdelatrisu.opsu.audio.SoundController.playHitSound(SoundController.java:353)
	at itdelatrisu.opsu.GameData.handleHitResult(GameData.java:1594)
	at itdelatrisu.opsu.GameData.sendHitResult(GameData.java:1652)
	at itdelatrisu.opsu.objects.Slider.hitResult(Slider.java:575)
	at itdelatrisu.opsu.objects.Slider.update(Slider.java:779)
	at itdelatrisu.opsu.states.Game.updateGame(Game.java:1144)
	at itdelatrisu.opsu.states.Game.runReplayFrame(Game.java:2170)
	at itdelatrisu.opsu.states.Game.addReplayFrameAndRun(Game.java:2153)
	at itdelatrisu.opsu.states.Game.update(Game.java:876)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:266)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Sat Jan 29 15:17:25 PST 2022 ERROR:Could not start a clip '/home/yusufkhan/Games/osu/Skins/osu!Default Skin/soft-hitfinish.wav'.
Sat Jan 29 15:17:25 PST 2022 ERROR:line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1052)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:213)
	at itdelatrisu.opsu.audio.MultiClip.start(MultiClip.java:135)
	at itdelatrisu.opsu.audio.SoundController.playClip(SoundController.java:312)
	at itdelatrisu.opsu.audio.SoundController.playHitSound(SoundController.java:361)
	at itdelatrisu.opsu.GameData.sendSliderTickResult(GameData.java:1448)
	at itdelatrisu.opsu.objects.Slider.mousePressed(Slider.java:606)
	at itdelatrisu.opsu.states.Game.sendGameKeyPress(Game.java:2204)
	at itdelatrisu.opsu.states.Game.runReplayFrame(Game.java:2166)
	at itdelatrisu.opsu.states.Game.addReplayFrameAndRun(Game.java:2153)
	at itdelatrisu.opsu.states.Game.gameKeyPressed(Game.java:1407)
	at itdelatrisu.opsu.states.Game.keyPressed(Game.java:1174)
	at org.newdawn.slick.state.StateBasedGame.keyPressed(StateBasedGame.java:445)
	at org.newdawn.slick.Input.poll(Input.java:1197)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)

```

**Comment by CloneWith** [comment]
> 403 for URL: http://b.ppy.sh/preview/0.mp3

It seems that opsu! cannot get the preview audio of a beatmap, which may be caused by a network problem.

> 406 for URL: https://storage.ripple.moe/d/873741

This should be the problem of Ripple beatmap mirror, try switch to another one available in the list.
