### ISSUE TITLE
Game.render() failure.

### ISSUE THREAD

**Issue by KotTheKitty** [itdelatrisu/opsu#624]
(info: using school computer with java 8 (v321))

**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_321
**OpenGL version:** 4.4.0 - Build 20.19.15.5126 (Intel)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
	at itdelatrisu.opsu.Container.start(Container.java:80)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
Caused by: java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at org.lwjgl.BufferUtils.createByteBuffer(BufferUtils.java:60)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.createVertexBuffer(LegacyCurveRenderState.java:308)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.initFBO(LegacyCurveRenderState.java:128)
	at itdelatrisu.opsu.render.LegacyCurveRenderState.<init>(LegacyCurveRenderState.java:118)
	at itdelatrisu.opsu.objects.curves.FakeCombinedCurve.draw(FakeCombinedCurve.java:63)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1706)
	at itdelatrisu.opsu.states.Game.render(Game.java:671)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```

**Comment by KotTheKitty** [comment]
oof, didn't see that the jre was listed, my bad

**Comment by KotTheKitty** [comment]
## Fixed

Just had to **clear ram** by closing programs.
