### ISSUE TITLE
** Uncaught Exception! ** problem on opsu! when using Windows 11 Pro

### ISSUE THREAD

**Issue by 1yoshipatty** [itdelatrisu/opsu#657]
**Version:** 0.16.1
**Build date:** 2018-06-03 19:24
**OS:** Windows 11 (amd64)
**JRE:** 1.8.0_411
**OpenGL version:** 4.4.0 - Build 20.19.15.5171 (Intel)
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.UnsatisfiedLinkError: C:\Users\1yoshipatty\AppData\Local\Temp\jna-559744571\jna3358480410889934216.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
	at com.sun.jna.Native.<clinit>(Native.java:140)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
	at com.sun.jna.platform.win32.WinReg$HKEY.<init>(WinReg.java:32)
	at com.sun.jna.platform.win32.WinReg.<clinit>(WinReg.java:61)
	at itdelatrisu.opsu.options.Options.getOsuInstallationDirectory(Options.java:211)
	at itdelatrisu.opsu.options.Options.getSkinRootDir(Options.java:1492)
	at itdelatrisu.opsu.options.Options.getSkinDir(Options.java:1545)
	at itdelatrisu.opsu.options.Options.loadSkin(Options.java:1511)
	at itdelatrisu.opsu.Utils.init(Utils.java:151)
	at itdelatrisu.opsu.states.Splash.init(Splash.java:105)
	at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:171)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
	at itdelatrisu.opsu.Container.runSetup(Container.java:112)
	at itdelatrisu.opsu.Container.start(Container.java:77)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:203)
```

It always does this when I try to launch opsu! 0.16.1
![image](https://github.com/itdelatrisu/opsu/assets/169515427/3759de6c-78e2-4b89-8318-5c9b6289d71c)

**Comment by Blaze-Corderz** [comment]
same

**Comment by SoxRegretsLife** [comment]
fr,compiling sucks man

**Comment by SoxRegretsLife** [comment]
Wait..this is fricking 7 yrs old and java is kinda old in the project, Thus I don't think the devs would rewrite it so I don't think we can solve it. Sorry bud

**Comment by SoxRegretsLife** [comment]
Unless you update your language to a older version
