### ISSUE TITLE
ArrayIndexOutOfBoundsException on funky sliders

### ISSUE THREAD

**Issue by chong601** [itdelatrisu/opsu#73]
(Extra note: this beatmap is designed to be weird anyway, but it may be reproducible on normal maps...)
Affected beatmap: [LeaF - Evanescent [Aspire]](https://osu.ppy.sh/b/529285)

The error message:
```
Sat Apr 11 22:55:35 SGT 2015 ERROR:Failed to create slider at index 161:
362,224,29985,2,0,B|362:298|362:298|362:294|362:294|362:301|362:301|362:298|362:298|362:305|362:305|362:301|362:301|362:308|362:308|362:305|362:305|362:312|362:312|362:308|362:308|362:316|362:316|362:312|362:312|362:319|362:319|362:316|362:316|362:323|362:323|362:319|362:319|362:327|362:327|362:323|362:323|362:330|362:330|362:327|362:327|362:334|362:334|362:330|362:330|362:337|362:337|362:334|362:334|362:341|362:341|362:337|362:337|362:345|362:345|362:341|362:341|362:348|362:348|362:345|362:345|362:352|362:352|362:348|362:348|362:356|362:356|362:352|362:352|362:356,1,225.00002
Sat Apr 11 22:55:35 SGT 2015 ERROR:0
java.lang.ArrayIndexOutOfBoundsException: 0
	at itdelatrisu.opsu.objects.curves.LinearBezier.<init>(LinearBezier.java:105)
	at itdelatrisu.opsu.objects.Slider.updatePosition(Slider.java:463)
	at itdelatrisu.opsu.objects.Slider.<init>(Slider.java:146)
	at itdelatrisu.opsu.states.Game.enter(Game.java:1074)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:93)
	at itdelatrisu.opsu.Container.start(Container.java:67)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:169)
Sat Apr 11 22:55:44 SGT 2015 ERROR:Failed to create slider at index 195:
154,165,37406,86,0,B|151:162|151:162|156:167|156:167|156:162|156:162|151:167|151:167|154:162|154:162|156:165|156:165|154:167|154:167|151:165|151:165,10,37.5,2|2|2|2|2|2|2|2|2|2|2,0:3|0:3|0:3|0:3|0:3|0:3|0:3|0:3|0:3|0:3|0:3,0:3:0:0:
Sat Apr 11 22:55:44 SGT 2015 ERROR:0
java.lang.ArrayIndexOutOfBoundsException: 0
	at itdelatrisu.opsu.objects.curves.LinearBezier.<init>(LinearBezier.java:105)
	at itdelatrisu.opsu.objects.Slider.updatePosition(Slider.java:463)
	at itdelatrisu.opsu.objects.Slider.<init>(Slider.java:146)
	at itdelatrisu.opsu.states.Game.enter(Game.java:1074)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:93)
	at itdelatrisu.opsu.Container.start(Container.java:67)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:169)
Sat Apr 11 22:55:44 SGT 2015 ERROR:Failed to create slider at index 424:
256,304,75459,6,0,B|256:241|256:241|256:246|256:246|256:234|256:234|256:237|256:237|256:224|256:224|256:229|256:229|256:214|256:214|256:224|256:224|256:210|256:210|256:215|256:215|256:188,1,168.75,2|0,0:0|0:0,0:0:0:0:
Sat Apr 11 22:55:44 SGT 2015 ERROR:0
java.lang.ArrayIndexOutOfBoundsException: 0
	at itdelatrisu.opsu.objects.curves.LinearBezier.<init>(LinearBezier.java:121)
	at itdelatrisu.opsu.objects.Slider.updatePosition(Slider.java:463)
	at itdelatrisu.opsu.objects.Slider.<init>(Slider.java:146)
	at itdelatrisu.opsu.states.Game.enter(Game.java:1074)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:93)
	at itdelatrisu.opsu.Container.start(Container.java:67)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:169)
Sat Apr 11 22:55:45 SGT 2015 ERROR:Failed to create slider at index 745:
256,192,124880,54,0,B|255:192|255:192|257:192|257:192|254:192,2,5.625,0|0|2,0:0|0:0|0:0,0:0:0:0:
Sat Apr 11 22:55:45 SGT 2015 ERROR:0
java.lang.ArrayIndexOutOfBoundsException: 0
	at itdelatrisu.opsu.objects.curves.LinearBezier.<init>(LinearBezier.java:94)
	at itdelatrisu.opsu.objects.Slider.updatePosition(Slider.java:463)
	at itdelatrisu.opsu.objects.Slider.<init>(Slider.java:146)
	at itdelatrisu.opsu.states.Game.enter(Game.java:1074)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:93)
	at itdelatrisu.opsu.Container.start(Container.java:67)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:169)
```

**Comment by itdelatrisu** [comment]
Fixed in #76.
