### ISSUE TITLE
Failed to load file 'count2s.wav'.

### ISSUE THREAD

**Issue by rodrigezBCL** [itdelatrisu/opsu#90]
**Version:** 0.9.0
**Build date:** 2015-05-17 19:41
**OS:** Linux (i386)
**JRE:** 1.7.0_79
**Error:** `Failed to load file 'count2s.wav'.`
**Stack trace:**
```
java.lang.IllegalArgumentException: Invalid format
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:142)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:99)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:283)
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:164)
	at itdelatrisu.opsu.audio.MultiClip.<init>(MultiClip.java:94)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:117)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:90)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:207)
	at itdelatrisu.opsu.states.Splash$1.run(Splash.java:109)
```

**Comment by itdelatrisu** [comment]
Almost certainly the same issue as #89.
